local helpers = require("helpers")

describe("the minimap button's geometry", function()
    local ns = helpers.loadAddon()

    it("puts angle 0 to the right and 90 at the top", function()
        local x, y = ns.MinimapButton.PositionFor(0, 80)
        assertNear(80, x)
        assertNear(0, y)
        x, y = ns.MinimapButton.PositionFor(90, 80)
        assertNear(0, x)
        assertNear(80, y)
    end)

    it("turns a cursor offset back into an angle between 0 and 360", function()
        assertNear(0, ns.MinimapButton.AngleFor(10, 0))
        assertNear(90, ns.MinimapButton.AngleFor(0, 10))
        assertNear(225, ns.MinimapButton.AngleFor(-10, -10))
    end)
end)

describe("the minimap button", function()
    it("sits on the minimap at its own angle, clear of BossLoot's", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual(env.Minimap, button:GetParent())
        assertEqual(200, ns.db.minimap.angle)
        assertEqual("Interface\\AddOns\\BankBags\\minimap", button.icon:GetTexture())
    end)

    it("opens and closes the bank on a click", function()
        local ns = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnClick(button, "LeftButton")
        assertTrue(ns.Window.Frame():IsShown())
        button.scripts.OnClick(button, "LeftButton")
        assertFalse(ns.Window.Frame():IsShown())
    end)

    it("clicks as it opens the bank, as the other addons' buttons do", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnClick(button, "LeftButton")
        assertEqual(env.SOUNDKIT.IG_CHARACTER_INFO_TAB, env.__sounds[1])
    end)

    it("hides and shows with /bb minimap, and remembers", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "minimap")
        assertFalse(ns.MinimapButton.Button():IsShown())
        assertTrue(ns.db.minimap.hide)
        helpers.command(env, "minimap")
        assertTrue(ns.MinimapButton.Button():IsShown())
    end)
end)
