// Writing the generated Lua data files, and the TOC lines that load them.

export const BEGIN = '# BEGIN GENERATED DATA';
export const END = '# END GENERATED DATA';

export function luaString(value) {
  return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
}

export function instanceFile(instance) {
  const lines = [
    '-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.',
    'local _, ns = ...',
    '',
    'ns.AddInstance({',
    `    key = ${luaString(instance.key)},`,
    `    name = ${luaString(instance.name)},`,
    `    kind = ${luaString(instance.kind)},`,
    `    levels = { ${instance.levels[0]}, ${instance.levels[1]} },`,
    '    bosses = {',
  ];

  for (const boss of instance.bosses) {
    lines.push('        {');
    lines.push(`            name = ${luaString(boss.name)},`);
    if (boss.wing) lines.push(`            wing = ${luaString(boss.wing)},`);
    lines.push('            loot = {');
    for (const entry of boss.loot) lines.push(`                { ${entry.id}, ${entry.chance} },`);
    lines.push('            },');
    lines.push('        },');
  }

  lines.push('    },');
  lines.push('    notable = {');
  for (const which of ['trash', 'objects']) {
    lines.push(`        ${which} = {`);
    for (const entry of instance.notable[which]) {
      lines.push(`            { ${entry.id}, ${entry.chance}, { ${entry.sources.map(luaString).join(', ')} } },`);
    }
    lines.push('        },');
  }
  lines.push('    },');
  lines.push('})');

  return `${lines.join('\n')}\n`;
}

// Replace everything between the markers with the given data files.
export function updateToc(tocText, files) {
  const lines = tocText.split(/\r?\n/);
  const begin = lines.indexOf(BEGIN);
  const end = lines.indexOf(END);
  if (begin < 0 || end < begin) throw new Error(`BossLoot.toc is missing the "${BEGIN}" / "${END}" markers`);

  return [...lines.slice(0, begin + 1), ...files.map((file) => `Data\\${file}`), ...lines.slice(end)].join('\n');
}
