// Recordings players made in WoW Forever, from saved-variables files put in
// tools/recordings/, baked into Data/Recorded.lua one recorder at a time. The
// addon leaves out the baked copy of the player's own recorder, so a
// player's loot is never counted twice.

import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { parseSavedVariables } from './savedvars.mjs';
import { luaString } from './lua.mjs';

const KEPT = ['sources', 'quests', 'merchants', 'crafts', 'items'];

/** Each recorder's recordings in the folder's *.lua files, in file-name order. */
export function readRecordings(dir) {
  if (!existsSync(dir)) return { recordings: [], warnings: [] };
  const byRecorder = new Map();
  const warnings = [];
  for (const file of readdirSync(dir).filter((name) => name.endsWith('.lua')).sort()) {
    let vars;
    try {
      vars = parseSavedVariables(readFileSync(join(dir, file), 'utf8'));
    } catch (error) {
      warnings.push(`${file}: ${error.message}`);
      continue;
    }
    const recorded = vars.BossLootDB?.recorded;
    if (!recorded || typeof recorded.recorder !== 'string') {
      warnings.push(`${file}: no BossLoot recordings`);
      continue;
    }
    const data = {};
    for (const key of KEPT) data[key] = recorded[key] ?? {};
    // A recorder sent twice: the later file, by name, wins.
    byRecorder.set(recorded.recorder, { recorder: recorded.recorder, data, file });
  }
  return { recordings: [...byRecorder.values()], warnings };
}

/** A value as Lua source. */
export function toLua(value, indent = '') {
  if (value === null || value === undefined) return 'nil';
  if (typeof value === 'string') return luaString(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  const keys = Object.keys(value);
  if (!keys.length) return '{}';
  const inner = `${indent}    `;
  const lines = keys.map((key) => {
    let written;
    if (/^-?\d+$/.test(key)) written = `[${key}]`;
    else if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) written = key;
    else written = `[${luaString(key)}]`;
    return `${inner}${written} = ${toLua(value[key], inner)},`;
  });
  return `{\n${lines.join('\n')}\n${indent}}`;
}

/** Data/Recorded.lua: each recorder's recordings handed to ns.AddRecordings. */
export function recordedFile(recordings) {
  const lines = [
    '-- Generated by tools/build-data.mjs from saved variables in tools/recordings. Do not edit.',
    '-- Loot, quest rewards, merchant goods and crafts recorded in WoW Forever, by recorder.',
    'local _, ns = ...',
    '',
  ];
  for (const { recorder, data } of recordings) {
    lines.push(`ns.AddRecordings(${luaString(recorder)}, ${toLua(data)})`, '');
  }
  return lines.join('\n');
}
