local helpers = require("helpers")

--- Logged in with the page on screen, as the options window shows it.
local function opened(saved)
    local ns, env = helpers.loggedIn(saved)
    ns.SettingsPanel.panel:Show()
    return ns, env, ns.SettingsPanel
end

--- The page and the board both open, to watch one follow the other.
local function bothOpen(saved)
    local ns, env, panel = opened(saved)
    helpers.command(env, "")
    return ns, env, panel, ns.Window.Frame()
end

describe("the settings page", function()
    it("is a page in the game's options, named LFGBoard", function()
        local _, env = helpers.loggedIn()
        assertEqual("LFGBoard", env.__settingsCategory.name)
    end)

    it("opens from /lfgb settings", function()
        local _, env = helpers.loggedIn()
        helpers.command(env, "settings")
        assertEqual("category-id", env.__openedCategory)
    end)

    it("is in /lfgb help", function()
        local _, env = helpers.loggedIn()
        helpers.command(env, "help")
        assertMatch("/lfgb settings", helpers.printed(env))
    end)

    it("heads the page with LFGBoard's own icon, its name and its version", function()
        local _, _, panel = opened()
        assertEqual("Interface\\AddOns\\LFGBoard\\minimap", panel.logo:GetTexture())
        assertEqual("LFGBoard", panel.title:GetText())
        assertEqual("Version 9.9.9", panel.version:GetText())
    end)

    it("hangs the first switch a clear gap under the hint, however far its words wrap", function()
        local _, _, panel = opened()
        local point, above, abovePoint, x, y = panel.nearLevel:GetPoint()
        assertEqual("TOPLEFT", point)
        assertEqual(panel.hint, above)
        assertEqual("BOTTOMLEFT", abovePoint)
        assertEqual(0, x, "the label where it was")
        assertEqual(-16, y, "the same gap as the other pages")
    end)

    it("hangs everything under the hint from it, so the rows below follow it down", function()
        local _, _, panel = opened()
        local below = { panel.nearLevel, panel.alerts, panel.completed, panel.roles.tank,
            panel.roles.healer, panel.roles.dps, panel.minimap, panel.openBoard }
        local lastY = 1
        for index, element in ipairs(below) do
            local _, above, _, _, y = element:GetPoint()
            assertEqual(panel.hint, above, "element " .. index)
            assertTrue(y <= lastY, "element " .. index .. " is not above the one before")
            lastY = y
        end
    end)

    it("is not built until it is first shown", function()
        local ns = helpers.loggedIn()
        assertNil(ns.SettingsPanel.nearLevel)
    end)

    it("shows what is saved when it opens", function()
        local _, _, panel = opened({ nearLevel = false, alerts = false, hideCompleted = false, minimap = { hide = true } })
        assertFalse(panel.nearLevel:GetChecked())
        assertFalse(panel.alerts:GetChecked())
        assertFalse(panel.completed:GetChecked())
        assertFalse(panel.minimap:GetChecked())
    end)

    it("ticks the roles this character's class plays the first time", function()
        local ns, env = helpers.loadAddon()
        env.__player.class, env.__player.classFile = "Priest", "PRIEST"
        helpers.login(env)
        local panel = ns.SettingsPanel
        panel.panel:Show()
        assertFalse(panel.roles.tank:GetChecked())
        assertTrue(panel.roles.healer:GetChecked())
        assertTrue(panel.roles.dps:GetChecked())
    end)
end)

describe("the page's switches", function()
    it("turn Near my level off and on, and the board's box follows", function()
        local ns, _, panel, frame = bothOpen()
        panel.nearLevel:Click()
        assertFalse(ns.db.nearLevel)
        assertFalse(frame.near:GetChecked())
        panel.nearLevel:Click()
        assertTrue(ns.db.nearLevel)
        assertTrue(frame.near:GetChecked())
    end)

    it("turn alerts off and on, and the board's box follows", function()
        local ns, _, panel, frame = bothOpen()
        panel.alerts:Click()
        assertFalse(ns.db.alerts)
        assertFalse(frame.alerts:GetChecked())
        panel.alerts:Click()
        assertTrue(ns.db.alerts)
        assertTrue(frame.alerts:GetChecked())
    end)

    it("show groups for completed quests and hide them again, and the board's box follows", function()
        local ns, _, panel, frame = bothOpen()
        assertTrue(panel.completed:GetChecked(), "hidden to begin with")
        panel.completed:Click()
        assertFalse(ns.db.hideCompleted)
        assertFalse(frame.completed:GetChecked())
        panel.completed:Click()
        assertTrue(ns.db.hideCompleted)
        assertTrue(frame.completed:GetChecked())
    end)

    it("hide the minimap button when unticked, show it when ticked, and remember", function()
        local ns, _, panel, frame = bothOpen()
        panel.minimap:Click()
        assertTrue(ns.db.minimap.hide)
        assertFalse(ns.MinimapButton.Button():IsShown())
        assertFalse(frame.minimap:GetChecked(), "the board's box follows")
        panel.minimap:Click()
        assertFalse(ns.db.minimap.hide)
        assertTrue(ns.MinimapButton.Button():IsShown())
        assertTrue(frame.minimap:GetChecked())
    end)

    it("switch this character's roles, and the board's boxes follow", function()
        local ns, _, panel, frame = bothOpen()
        assertTrue(panel.roles.healer:GetChecked(), "a druid heals")
        panel.roles.healer:Click()
        assertFalse(ns.Roles().healer)
        assertFalse(frame.roles.healer:GetChecked())
        assertTrue(ns.Roles().tank, "the other roles left alone")
    end)

    it("hide a group that wants only a role switched off here", function()
        local _, env, panel, frame = bothOpen()
        helpers.say(env, "Garrok", "LFM DM need heals")
        assertTrue(frame.rows[1]:IsShown())
        panel.roles.healer:Click()
        assertFalse(frame.rows[1]:IsShown())
    end)
end)

describe("the page following the board", function()
    it("ticks and unticks with the board's own boxes", function()
        local ns, _, panel, frame = bothOpen()
        frame.near:Click()
        assertFalse(panel.nearLevel:GetChecked())
        frame.alerts:Click()
        assertFalse(panel.alerts:GetChecked())
        frame.completed:Click()
        assertFalse(panel.completed:GetChecked())
        frame.minimap:Click()
        assertFalse(panel.minimap:GetChecked())
        frame.roles.tank:Click()
        assertFalse(panel.roles.tank:GetChecked())
        assertFalse(ns.Roles().tank)
    end)

    it("follows /lfgb minimap", function()
        local _, env, panel = opened()
        helpers.command(env, "minimap")
        assertFalse(panel.minimap:GetChecked())
        helpers.command(env, "minimap")
        assertTrue(panel.minimap:GetChecked())
    end)
end)

describe("the Open the board button", function()
    it("opens the board", function()
        local ns, _, panel = opened()
        assertEqual("Open the board", panel.openBoard:GetText())
        panel.openBoard:Click()
        assertTrue(ns.Window.Frame():IsShown())
    end)

    it("leaves the board open when it is open already", function()
        local ns, _, panel = bothOpen()
        panel.openBoard:Click()
        assertTrue(ns.Window.Frame():IsShown())
    end)
end)

describe("the minimap button's right-click", function()
    it("opens the settings, and a left-click still opens the board", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual("RightButtonUp", button.clicks[2])

        button:Click("RightButton")
        assertEqual("category-id", env.__openedCategory)
        assertNil(ns.Window.Frame(), "the board left closed")

        button:Click("LeftButton")
        assertTrue(ns.Window.Frame():IsShown())
    end)

    it("says so on the tooltip", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnEnter(button)
        assertMatch("Right%-click for the settings", table.concat(env.GameTooltip.lines, "\n"))
    end)
end)

describe("closing the page", function()
    -- Opening a page by command leaves the client queued to fall back to the
    -- game menu when it closes, which is not where the player came from.
    it("does not leave the game menu behind", function()
        local ns, env = helpers.loggedIn()
        ns.OpenSettings()
        env.SettingsPanel.scripts.OnHide(env.SettingsPanel)
        env.GameMenuFrame:Show()
        assertFalse(env.GameMenuFrame:IsShown(), "gone before a frame is drawn")
    end)

    it("leaves the game menu alone when the player opened the page from it", function()
        local ns, env = helpers.loggedIn()
        ns.OpenSettings()
        env.SettingsPanel.scripts.OnHide(env.SettingsPanel)
        env.__runTimers()

        env.SettingsPanel.scripts.OnHide(env.SettingsPanel)
        env.GameMenuFrame:Show()
        env.__runTimers()
        assertTrue(env.GameMenuFrame:IsShown(), "left where the client put it")
    end)
end)
