local helpers = require("helpers")

local function chars(ns)
    return ns.db.chars["Skyler-Aldira"]
end

describe("loading", function()
    it("says it has loaded, with the command", function()
        local _, env = helpers.loggedIn()
        assertMatch("Loaded%. Type /tp", helpers.printed(env))
    end)

    it("lists its commands on /tp help", function()
        local _, env = helpers.loggedIn()
        helpers.clearPrinted(env)
        helpers.command(env, "help")
        local printed = helpers.printed(env)
        assertMatch("/tp probe", printed)
        assertMatch("/tp new", printed)
    end)

    it("names an unknown command", function()
        local _, env = helpers.loggedIn()
        helpers.command(env, "fly")
        assertMatch("Unknown command: fly", helpers.printed(env))
    end)

    it("starts with every setting on but Learn next", function()
        local ns = helpers.loggedIn()
        assertTrue(ns.db.remind)
        assertTrue(ns.db.overlay)
        assertFalse(ns.db.learn)
        assertFalse(ns.db.minimap.hide)
    end)

    it("keeps what was saved", function()
        local saved = { learn = true, chars = { ["Skyler-Aldira"] = {
            active = "Bear", plans = { Bear = { class = "DRUID", points = { { 2, 2 } } } },
        } } }
        local ns = helpers.loggedIn(saved)
        assertTrue(ns.db.learn)
        local plan, name = ns.Plans.Active()
        assertEqual("Bear", name)
        assertEqual(1, #plan.points)
    end)
end)

describe("plans", function()
    it("makes a first plan for the character's class", function()
        local ns = helpers.loggedIn()
        local plan, name = ns.Plans.Active()
        assertEqual("Plan 1", name)
        assertEqual("DRUID", plan.class)
        assertEqual(0, #plan.points)
        assertEqual("Plan 1", chars(ns).active)
    end)

    it("keeps each character's plans apart", function()
        local ns, env = helpers.loggedIn()
        ns.Plans.Active()
        env.__player.name = "Other"
        ns.Plans.New("Healing")
        assertEqual("Plan 1", chars(ns).active)
        assertEqual("Healing", ns.db.chars["Other-Aldira"].active)
    end)

    it("makes a new plan the active one", function()
        local ns = helpers.loggedIn()
        ns.Plans.Active()
        assertTrue(ns.Plans.New("Feral levelling"))
        local _, name = ns.Plans.Active()
        assertEqual("Feral levelling", name)
        assertEqual("Feral levelling, Plan 1", table.concat(ns.Plans.Names(), ", "))
    end)

    it("refuses an empty or taken name", function()
        local ns = helpers.loggedIn()
        ns.Plans.Active()
        local ok, why = ns.Plans.New("   ")
        assertFalse(ok)
        assertEqual("A plan needs a name.", why)
        local ok2, why2 = ns.Plans.New("Plan 1")
        assertFalse(ok2)
        assertEqual("There is already a plan called Plan 1.", why2)
    end)

    it("renames the active plan and keeps it active", function()
        local ns = helpers.loggedIn()
        local plan = ns.Plans.Active()
        table.insert(plan.points, { 2, 2 })
        assertTrue(ns.Plans.Rename("Bear"))
        local renamed, name = ns.Plans.Active()
        assertEqual("Bear", name)
        assertEqual(1, #renamed.points)
        assertNil(chars(ns).plans["Plan 1"])
    end)

    it("selects another plan", function()
        local ns = helpers.loggedIn()
        ns.Plans.Active()
        ns.Plans.New("Bear")
        ns.Plans.Select("Plan 1")
        local _, name = ns.Plans.Active()
        assertEqual("Plan 1", name)
    end)

    it("deletes the active plan and falls back to another", function()
        local ns = helpers.loggedIn()
        ns.Plans.Active()
        ns.Plans.New("Bear")
        ns.Plans.Delete()
        local _, name = ns.Plans.Active()
        assertEqual("Plan 1", name)
        assertNil(chars(ns).plans.Bear)
    end)

    it("starts afresh when the last plan is deleted", function()
        local ns = helpers.loggedIn()
        local plan = ns.Plans.Active()
        table.insert(plan.points, { 2, 2 })
        ns.Plans.Delete()
        local fresh, name = ns.Plans.Active()
        assertEqual("Plan 1", name)
        assertEqual(0, #fresh.points)
    end)

    it("tells whoever listens when a plan changes", function()
        local ns = helpers.loggedIn()
        local heard = 0
        ns.OnChange(function() heard = heard + 1 end)
        ns.Plans.New("Bear")
        assertTrue(heard > 0)
    end)

    it("has commands for new, rename and delete", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "new Feral levelling")
        assertEqual("Feral levelling", select(2, ns.Plans.Active()))
        helpers.command(env, "rename Bear")
        assertEqual("Bear", select(2, ns.Plans.Active()))
        helpers.command(env, "delete")
        assertNil(chars(ns).plans.Bear)
        helpers.command(env, "new")
        assertMatch("A plan needs a name", helpers.printed(env))
    end)
end)
