local helpers = require("helpers")

describe("the minimap button's geometry", function()
    local ns = helpers.loadAddon()

    it("puts angle 0 to the right and 90 at the top", function()
        local x, y = ns.MinimapButton.PositionFor(0, 80)
        assertNear(80, x)
        assertNear(0, y)
        x, y = ns.MinimapButton.PositionFor(90, 80)
        assertNear(0, x)
        assertNear(80, y)
    end)

    it("turns a cursor offset back into an angle between 0 and 360", function()
        assertNear(0, ns.MinimapButton.AngleFor(10, 0))
        assertNear(90, ns.MinimapButton.AngleFor(0, 10))
        assertNear(225, ns.MinimapButton.AngleFor(-10, -10))
    end)
end)

describe("the minimap button", function()
    it("sits on the minimap at its own angle, with TalentPlanner's own icon", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual(env.Minimap, button:GetParent())
        assertEqual(325, ns.db.minimap.angle)
        assertEqual("Interface\\AddOns\\TalentPlanner\\minimap", button.icon:GetTexture())
    end)

    it("opens the planner on a click, and closes it on the next", function()
        local ns = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button:Click("LeftButton")
        assertTrue(ns.Planner.Frame():IsShown())
        button:Click("LeftButton")
        assertFalse(ns.Planner.Frame():IsShown())
    end)

    it("opens the settings on a right-click", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual("RightButtonUp", button.clicks[2], "asks for right-clicks too")
        button:Click("RightButton")
        assertEqual("category-id", env.__openedCategory)
    end)

    it("says what its clicks do in its tooltip", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnEnter(button)
        assertEqual("TalentPlanner", env.GameTooltip:GetText())
        assertMatch("planner", table.concat(env.GameTooltip.lines, "\n"))
    end)

    it("hides and shows with /tp minimap, says so, and remembers", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "minimap")
        assertFalse(ns.MinimapButton.Button():IsShown())
        assertTrue(ns.db.minimap.hide)
        assertMatch("/tp minimap brings it back", helpers.printed(env))
        helpers.command(env, "minimap")
        assertTrue(ns.MinimapButton.Button():IsShown())
    end)

    it("stays hidden at login when it was hidden", function()
        local ns = helpers.loggedIn({ minimap = { hide = true } })
        assertFalse(ns.MinimapButton.Button():IsShown())
    end)

    it("slides round the rim when dragged, and keeps its place", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        env.GetCursorPosition = function() return 0, 10 end
        button.scripts.OnDragStart(button)
        button.scripts.OnUpdate(button)
        button.scripts.OnDragStop(button)
        assertNear(90, ns.db.minimap.angle)
        assertNil(button.scripts.OnUpdate)
    end)
end)
