local helpers = require("helpers")

local Plan = helpers.loadPure("Plan.lua").Plan
local trees = helpers.trees
local points = helpers.points

-- Indexes into the stub's druid.
local BALANCE, FERAL, RESTO = 1, 2, 3
local FEROCITY, INSTINCT, THICK_HIDE, CLAWS, CHARGE, PRIMAL_FURY, HEART = 1, 2, 3, 5, 6, 9, 10

describe("Plan, loaded on its own", function()
    it("needs nothing from the game", function()
        assertTrue(Plan ~= nil)
        assertEqual(51, Plan.MAX)
    end)
end)

describe("adding a point", function()
    it("appends a talent with nothing in its way", function()
        local list = {}
        assertTrue(Plan.Add(trees(), list, FERAL, INSTINCT))
        assertEqual(1, #list)
        assertEqual(FERAL, list[1][1])
        assertEqual(INSTINCT, list[1][2])
    end)

    it("stops at the talent's max rank", function()
        local list = points("2.2x5")
        local ok, why = Plan.Add(trees(), list, FERAL, INSTINCT)
        assertFalse(ok)
        assertEqual("Feral Instinct is already at 5/5.", why)
        assertEqual(5, #list)
    end)

    it("needs five points in the tree before a tier 2 talent", function()
        local list = points("2.2x4")
        local ok, why = Plan.Add(trees(), list, FERAL, THICK_HIDE)
        assertFalse(ok)
        assertEqual("Thick Hide needs 5 points in Feral Combat first.", why)
        assertTrue(Plan.Add(trees(), points("2.2x5"), FERAL, THICK_HIDE))
    end)

    it("counts only points in the same tree for the tier", function()
        local ok, why = Plan.Add(trees(), points("1.1x5"), FERAL, THICK_HIDE)
        assertFalse(ok)
        assertMatch("5 points in Feral Combat", why)
    end)

    it("needs ten for tier 3 and twenty for tier 5", function()
        local _, why = Plan.Add(trees(), points("2.1x5", "2.2x4"), FERAL, CLAWS)
        assertEqual("Sharpened Claws needs 10 points in Feral Combat first.", why)
        local _, why5 = Plan.Add(trees(), points("2.1x5", "2.2x5", "2.3x5"), FERAL, HEART)
        assertEqual("Heart of the Wild needs 20 points in Feral Combat first.", why5)
    end)

    it("needs the prerequisite at full rank before it", function()
        local list = points("2.1x5", "2.2x5", "2.3x5", "2.5x4")
        local ok, why = Plan.Add(trees(), list, FERAL, PRIMAL_FURY)
        assertFalse(ok)
        assertEqual("Primal Fury needs Sharpened Claws at 5/5 first.", why)
        assertTrue(Plan.Add(trees(), points("2.1x5", "2.2x5", "2.3x5", "2.5x5"), FERAL, PRIMAL_FURY))
    end)

    it("takes a same-tier prerequisite too", function()
        local _, why = Plan.Add(trees(), {}, BALANCE, 3)
        assertEqual("Improved Nature's Grasp needs Nature's Grasp at 1/1 first.", why)
        assertTrue(Plan.Add(trees(), points("1.2"), BALANCE, 3))
    end)

    it("holds no more than 51 points", function()
        -- Feral holds 46; five Starlight Wrath make 51.
        local list = points("2.1x5", "2.2x5", "2.3x5", "2.4x5", "2.5x5", "2.6", "2.7x5", "2.8x5", "2.9x5", "2.10x5", "1.1x5")
        assertEqual(51, #list)
        assertTrue(Plan.Validate(trees(), list))
        local ok, why = Plan.Add(trees(), list, RESTO, 1)
        assertFalse(ok)
        assertEqual("The plan is full: 51 points.", why)
    end)

    it("refuses a talent the tree does not have", function()
        local ok, why = Plan.Add(trees(), {}, FERAL, 12)
        assertFalse(ok)
        assertEqual("Tree 2 has no talent 12.", why)
        local _, whyTab = Plan.Add(trees(), {}, 4, 1)
        assertEqual("Tree 4 has no talent 1.", whyTab)
    end)
end)

describe("a whole plan", function()
    it("is valid when every point is", function()
        assertTrue(Plan.Validate(trees(), points("2.2x5", "2.3x5", "2.6")))
        assertTrue(Plan.Validate(trees(), {}))
    end)

    it("names the first point that breaks a rule", function()
        local ok, index, why = Plan.Validate(trees(), points("2.2x4", "2.3", "2.2"))
        assertFalse(ok)
        assertEqual(5, index)
        assertEqual("Thick Hide needs 5 points in Feral Combat first.", why)
    end)

    it("describes a point by number, level and talent", function()
        assertEqual("Point 7 (level 16), Feral Instinct", Plan.Describe(trees(), 7, { FERAL, INSTINCT }))
        assertEqual("Point 3 (level 12), tree 2 talent 40", Plan.Describe(trees(), 3, { FERAL, 40 }))
    end)
end)

describe("levels", function()
    it("takes point n at level n + 9", function()
        assertEqual(10, Plan.LevelOf(1))
        assertEqual(60, Plan.LevelOf(51))
    end)

    it("lists the levels a talent's points are taken at", function()
        local list = points("2.1", "2.2", "2.1", "2.2", "2.1", "2.2", "2.1")
        local levels = Plan.Levels(list, FERAL, INSTINCT)
        assertEqual("11, 13, 15", table.concat(levels, ", "))
        assertEqual(0, #Plan.Levels(list, FERAL, THICK_HIDE))
    end)

    it("counts a talent's points, all or the first few", function()
        local list = points("2.1", "2.2", "2.1", "2.2")
        assertEqual(2, Plan.Count(list, FERAL, FEROCITY))
        assertEqual(1, Plan.Count(list, FERAL, FEROCITY, 2))
        assertEqual(4, Plan.TreeCount(list, FERAL))
        assertEqual(0, Plan.TreeCount(list, BALANCE))
    end)
end)

describe("removing a point", function()
    it("takes out the talent's last planned point", function()
        local list = points("2.2", "2.1", "2.2", "2.1")
        local ok, index = Plan.Remove(trees(), list, FERAL, INSTINCT)
        assertTrue(ok)
        assertEqual(3, index)
        assertEqual(3, #list)
        assertEqual(1, Plan.Count(list, FERAL, INSTINCT))
        assertEqual(FEROCITY, list[3][2])
    end)

    it("refuses when a later point needs it as a prerequisite, naming that point", function()
        local list = points("2.1x5", "2.2x5", "2.3x5", "2.5x5", "2.9")
        local ok, why = Plan.Remove(trees(), list, FERAL, CLAWS)
        assertFalse(ok)
        assertEqual("Point 21 (level 30), Primal Fury, depends on it.", why)
        assertEqual(21, #list, "nothing changed")
    end)

    it("refuses when a later point loses its tier", function()
        local list = points("2.2x5", "2.3")
        local ok, why = Plan.Remove(trees(), list, FERAL, INSTINCT)
        assertFalse(ok)
        assertEqual("Point 6 (level 15), Thick Hide, depends on it.", why)
        assertEqual(6, #list)
    end)

    it("leaves a plan without the talent as it is", function()
        local list = points("2.2")
        local ok, why = Plan.Remove(trees(), list, FERAL, CHARGE)
        assertFalse(ok)
        assertEqual("Feral Charge is not in the plan.", why)
        assertEqual(1, #list)
    end)

    it("undoes the last point", function()
        local list = points("2.2", "2.1")
        local removed = Plan.Undo(list)
        assertEqual(FEROCITY, removed[2])
        assertEqual(1, #list)
        Plan.Undo(list)
        assertNil(Plan.Undo(list))
    end)
end)

describe("the next point", function()
    it("is the first point when nothing is learned", function()
        local list = points("2.2", "2.2", "2.1")
        local n, tab, index, rank = Plan.Next(list, Plan.RanksOf(trees()))
        assertEqual(1, n)
        assertEqual(FERAL, tab)
        assertEqual(INSTINCT, index)
        assertEqual(1, rank)
    end)

    it("skips points already learned", function()
        local list = points("2.2", "2.2", "2.1")
        local n, _, index, rank = Plan.Next(list, Plan.RanksOf(trees({ [2] = { [2] = 1 } })))
        assertEqual(2, n)
        assertEqual(INSTINCT, index)
        assertEqual(2, rank)
    end)

    it("skips points already learned out of the plan's order", function()
        local list = points("2.2", "2.2", "2.1")
        local n, _, index = Plan.Next(list, Plan.RanksOf(trees({ [2] = { [1] = 1, [2] = 1 } })))
        assertEqual(2, n)
        assertEqual(INSTINCT, index)
    end)

    it("is nothing when the plan is done", function()
        assertNil(Plan.Next(points("2.2"), Plan.RanksOf(trees({ [2] = { [2] = 1 } }))))
        assertNil(Plan.Next({}, Plan.RanksOf(trees())))
    end)
end)

describe("talents over the plan", function()
    it("marks a talent with more points than the plan had by then", function()
        local list = points("2.2", "2.2", "2.1")
        -- Two points spent: the plan had Feral Instinct 2/5 by then.
        local over = Plan.Over(list, Plan.RanksOf(trees({ [2] = { [1] = 1, [2] = 1 } })))
        assertTrue(over[FERAL] and over[FERAL][FEROCITY])
        assertFalse(over[FERAL] and over[FERAL][INSTINCT])
    end)

    it("marks nothing for a player on plan", function()
        local over = Plan.Over(points("2.2", "2.2", "2.1"), Plan.RanksOf(trees({ [2] = { [2] = 2 } })))
        assertNil(next(over))
    end)
end)
