local helpers = require("helpers")

local function opened(saved, prepare)
    local ns, env = helpers.loggedIn(saved, prepare)
    helpers.command(env, "")
    return ns, env, ns.Planner.Frame()
end

local function talent(frame, tab, index)
    return frame.trees[tab].buttons[index]
end

local function points(ns)
    return ns.Plans.Active().points
end

describe("the planner window", function()
    it("opens and closes with /tp", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "")
        assertTrue(ns.Planner.Frame():IsShown())
        helpers.command(env, "")
        assertFalse(ns.Planner.Frame():IsShown())
    end)

    it("is BossLoot's frame: the options window's, its title, logo and a solid background", function()
        local _, env, frame = opened()
        assertEqual("SettingsFrameTemplate", frame.template)
        assertEqual("Talent Planner", frame.title:GetText())
        assertEqual("Interface\\AddOns\\TalentPlanner\\minimap", frame.logo:GetTexture())
        assertEqual(1, frame.background.color[4])
        local found = false
        for _, name in ipairs(env.UISpecialFrames) do
            found = found or name == "TalentPlannerFrame"
        end
        assertTrue(found, "closes on Escape")
    end)

    it("falls back to a frame of its own without the options window's template", function()
        local _, _, frame = opened(nil, function(env) env.__missingTemplates.SettingsFrameTemplate = true end)
        assertEqual("Talent Planner", frame.title:GetText())
        assertTrue(frame.close ~= nil)
        frame.close:Click()
        assertFalse(frame:IsShown())
    end)

    it("draws the three trees with every talent's icon", function()
        local _, _, frame = opened()
        assertEqual("Balance", frame.trees[1].header:GetText())
        assertEqual("Feral Combat", frame.trees[2].header:GetText())
        assertEqual("Restoration", frame.trees[3].header:GetText())
        assertEqual("icon-2-10", talent(frame, 2, 10).icon:GetTexture())
        assertEqual("0/5", talent(frame, 2, 2).count:GetText())
    end)

    it("draws each prerequisite as a line", function()
        local _, _, frame = opened()
        assertTrue(#frame.trees[2].lines >= 2)
    end)

    it("adds a point on a left-click", function()
        local ns, _, frame = opened()
        talent(frame, 2, 2):Click("LeftButton")
        talent(frame, 2, 2):Click("LeftButton")
        assertEqual(2, #points(ns))
        assertEqual("2/5", talent(frame, 2, 2).count:GetText())
        assertEqual("10", talent(frame, 2, 2).level:GetText())
        assertEqual("2/51", frame.total:GetText())
    end)

    it("says why a point cannot be added, and adds nothing", function()
        local ns, _, frame = opened()
        talent(frame, 2, 3):Click("LeftButton")
        assertEqual(0, #points(ns))
        assertMatch("Thick Hide needs 5 points in Feral Combat first%.", frame.status:GetText())
    end)

    it("takes a point off on a right-click", function()
        local ns, _, frame = opened()
        talent(frame, 2, 2):Click("LeftButton")
        talent(frame, 2, 1):Click("LeftButton")
        talent(frame, 2, 2):Click("RightButton")
        assertEqual(1, #points(ns))
        assertEqual("0/5", talent(frame, 2, 2).count:GetText())
        assertEqual("1/5", talent(frame, 2, 1).count:GetText())
    end)

    it("names the later point that keeps a point in, and changes nothing", function()
        local ns, _, frame = opened()
        for _ = 1, 5 do talent(frame, 2, 2):Click("LeftButton") end
        talent(frame, 2, 3):Click("LeftButton")
        talent(frame, 2, 2):Click("RightButton")
        assertEqual(6, #points(ns))
        assertMatch("Point 6 %(level 15%), Thick Hide, depends on it%.", frame.status:GetText())
    end)

    it("shows the game's talent tooltip and the levels planned", function()
        local _, env, frame = opened()
        local button = talent(frame, 2, 2)
        button:Click("LeftButton")
        talent(frame, 2, 1):Click("LeftButton")
        button:Click("LeftButton")
        button.scripts.OnEnter(button)
        assertEqual(2, env.GameTooltip.talent[1])
        assertEqual(2, env.GameTooltip.talent[2])
        assertMatch("Planned at levels 10, 12", table.concat(env.GameTooltip.lines, "\n"))
        assertTrue(env.GameTooltip:IsShown())
    end)

    it("names the talent itself when the tooltip has no SetTalent", function()
        local _, env, frame = opened(nil, function(env) env.__noSetTalent = true end)
        local button = talent(frame, 2, 2)
        button.scripts.OnEnter(button)
        assertEqual("Feral Instinct", env.GameTooltip:GetText())
        assertMatch("Not in the plan", table.concat(env.GameTooltip.lines, "\n"))
    end)

    it("undoes the last point", function()
        local ns, _, frame = opened()
        talent(frame, 2, 2):Click("LeftButton")
        talent(frame, 2, 1):Click("LeftButton")
        frame.undo:Click()
        assertEqual(1, #points(ns))
        assertEqual(2, points(ns)[1][2])
    end)

    it("clears the plan only once the player says so", function()
        local ns, _, frame = opened()
        talent(frame, 2, 2):Click("LeftButton")
        frame.clear:Click()
        local dialog = ns.Planner.Dialog()
        assertTrue(dialog:IsShown())
        assertEqual(1, #points(ns), "nothing cleared yet")
        dialog.cancel:Click()
        assertEqual(1, #points(ns))
        frame.clear:Click()
        dialog.accept:Click()
        assertEqual(0, #points(ns))
        assertFalse(dialog:IsShown())
        assertEqual("0/51", frame.total:GetText())
    end)

    it("flags a saved plan that breaks a rule", function()
        local saved = { chars = { ["Skyler-Aldira"] = {
            active = "Old", plans = { Old = { class = "DRUID", points = { { 2, 2 }, { 2, 12 } } } },
        } } }
        local _, _, frame = opened(saved)
        assertMatch("Point 2 %(level 11%)", frame.status:GetText())
    end)

    it("says why instead of drawing on a client without the talent calls", function()
        local _, _, frame = opened(nil, function(env) env.GetTalentPrereqs = nil end)
        assertTrue(frame.message:IsShown())
        assertMatch("GetTalentPrereqs", frame.message:GetText())
        assertFalse(frame.trees[1] and frame.trees[1].panel:IsShown() or false)
    end)
end)

describe("export and import", function()
    it("shows the plan as text, selected for copying", function()
        local ns, _, frame = opened()
        talent(frame, 2, 2):Click("LeftButton")
        frame.export:Click()
        local dialog = ns.Planner.Dialog()
        assertTrue(dialog:IsShown())
        assertEqual("TP1:DRUID:22", dialog.box:GetText())
        assertTrue(dialog.box.highlighted)
        assertTrue(dialog.box.focused)
    end)

    it("imports a pasted plan as the active one", function()
        local ns, _, frame = opened()
        frame.import:Click()
        local dialog = ns.Planner.Dialog()
        assertEqual("", dialog.box:GetText())
        dialog.box:SetText("TP1:DRUID:2222")
        dialog.accept:Click()
        assertFalse(dialog:IsShown())
        assertEqual("Imported", select(2, ns.Plans.Active()))
        assertEqual("2/5", talent(frame, 2, 2).count:GetText())
    end)

    it("keeps the box open and says why a string is refused", function()
        local ns, _, frame = opened()
        frame.import:Click()
        local dialog = ns.Planner.Dialog()
        dialog.box:SetText("TP1:MAGE:11")
        dialog.accept:Click()
        assertTrue(dialog:IsShown())
        assertMatch("for a MAGE", dialog.text:GetText())
    end)

    it("imports on Enter too", function()
        local ns, _, frame = opened()
        frame.import:Click()
        local dialog = ns.Planner.Dialog()
        dialog.box:SetText("TP1:DRUID:22")
        dialog.box.scripts.OnEnterPressed(dialog.box)
        assertEqual("Imported", select(2, ns.Plans.Active()))
    end)
end)

describe("the plan menu", function()
    it("shows the plan's name on the selector", function()
        local _, _, frame = opened()
        assertMatch("Plan 1", frame.selector:GetText())
    end)

    it("lists the plans and switches between them", function()
        local ns, env, frame = opened()
        ns.Plans.New("Bear")
        frame.selector:Click()
        local entry = env.__menu:Find("Plan 1")
        assertTrue(entry ~= nil)
        entry.onClick()
        assertEqual("Plan 1", select(2, ns.Plans.Active()))
        assertMatch("Plan 1", frame.selector:GetText())
    end)

    it("starts a new plan by name", function()
        local ns, env, frame = opened()
        frame.selector:Click()
        env.__menu:Find("New plan..."):onClick()
        local dialog = ns.Planner.Dialog()
        dialog.box:SetText("Feral levelling")
        dialog.accept:Click()
        assertEqual("Feral levelling", select(2, ns.Plans.Active()))
    end)

    it("refuses a taken name in the box", function()
        local ns, env, frame = opened()
        frame.selector:Click()
        env.__menu:Find("New plan..."):onClick()
        local dialog = ns.Planner.Dialog()
        dialog.box:SetText("Plan 1")
        dialog.accept:Click()
        assertTrue(dialog:IsShown())
        assertMatch("already a plan called Plan 1", dialog.text:GetText())
    end)

    it("renames the plan", function()
        local ns, env, frame = opened()
        frame.selector:Click()
        env.__menu:Find("Rename..."):onClick()
        local dialog = ns.Planner.Dialog()
        assertEqual("Plan 1", dialog.box:GetText())
        dialog.box:SetText("Bear")
        dialog.accept:Click()
        assertEqual("Bear", select(2, ns.Plans.Active()))
    end)

    it("deletes the plan once the player says so", function()
        local ns, env, frame = opened()
        ns.Plans.New("Bear")
        frame.selector:Click()
        env.__menu:Find("Delete..."):onClick()
        ns.Planner.Dialog().accept:Click()
        assertEqual("Plan 1", select(2, ns.Plans.Active()))
    end)

    it("uses EasyMenu on a client without MenuUtil", function()
        local ns, env, frame = opened(nil, helpers.useEasyMenu)
        ns.Plans.New("Bear")
        frame.selector:Click()
        local picked
        for _, entry in ipairs(env.__easyMenu) do
            if entry.text == "Plan 1" then picked = entry end
        end
        assertTrue(picked ~= nil)
        picked.func()
        assertEqual("Plan 1", select(2, ns.Plans.Active()))
    end)

    it("cycles through the plans on a client with no menu", function()
        local ns, _, frame = opened(nil, helpers.useNoMenu)
        ns.Plans.New("Bear")
        frame.selector:Click()
        assertEqual("Plan 1", select(2, ns.Plans.Active()))
        frame.selector:Click()
        assertEqual("Bear", select(2, ns.Plans.Active()))
    end)
end)

describe("the Learn next button", function()
    it("is hidden while the setting is off", function()
        local _, _, frame = opened()
        assertFalse(frame.learn:IsShown())
    end)

    it("shows with the setting on and learns the next point", function()
        local ns, env, frame = opened({ learn = true }, function(env) env.__unspent = 1 end)
        assertTrue(frame.learn:IsShown())
        talent(frame, 2, 2):Click("LeftButton")
        frame.learn:Click()
        assertEqual(1, env.__ranks[2][2])
    end)

    it("stays hidden on a client without LearnTalent", function()
        local _, _, frame = opened({ learn = true }, function(env) env.LearnTalent = nil end)
        assertFalse(frame.learn:IsShown())
    end)

    it("says why it did nothing", function()
        local _, env, frame = opened({ learn = true }, function(env) env.__unspent = 1 end)
        talent(frame, 2, 2):Click("LeftButton")
        env.__inCombat = true
        frame.learn:Click()
        assertEqual("Not in combat.", frame.status:GetText())
    end)
end)
