-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "BlackfathomDeeps",
    name = "Blackfathom Deeps",
    kind = "dungeon",
    levels = { 24, 32 },
    bosses = {
        {
            name = "Ghamoo-ra",
            loot = {
                { 6907, 50 },
                { 6908, 50 },
            },
        },
        {
            name = "Lady Sarevess",
            loot = {
                { 888, 33.33 },
                { 3078, 33.33 },
                { 11121, 33.33 },
            },
        },
        {
            name = "Gelihast",
            loot = {
                { 6906, 50 },
                { 6905, 50 },
                { 1470, 15 },
            },
        },
        {
            name = "Lorgus Jett",
            loot = {
                { 3416, 0.24 },
                { 1454, 0.1 },
                { 2271, 0.1 },
                { 3414, 0.1 },
                { 1486, 0.04 },
                { 3413, 0.04 },
                { 3415, 0.04 },
                { 3417, 0.04 },
            },
        },
        {
            name = "Baron Aquanis",
            loot = {
                { 1481, 0.08 },
                { 3414, 0.08 },
                { 2271, 0.07 },
                { 3416, 0.05 },
                { 1491, 0.04 },
                { 1454, 0.02 },
                { 16782, 100 },
            },
        },
        {
            name = "Twilight Lord Kelris",
            loot = {
                { 1155, 50 },
                { 6903, 50 },
            },
        },
        {
            name = "Old Serra'kis",
            loot = {
                { 6901, 33.33 },
                { 6904, 33.33 },
                { 6902, 33.33 },
            },
        },
        {
            name = "Aku'mai",
            loot = {
                { 6909, 33.33 },
                { 6910, 33.33 },
                { 6911, 33.33 },
            },
        },
    },
    notable = {
        trash = {
        },
        objects = {
        },
    },
})
