-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "Gnomeregan",
    name = "Gnomeregan",
    kind = "dungeon",
    levels = { 29, 38 },
    bosses = {
        {
            name = "Grubbis",
            loot = {
                { 9445, 10 },
                { 9308, 15 },
            },
        },
        {
            name = "Viscous Fallout",
            loot = {
                { 9452, 33.33 },
                { 9453, 33.33 },
                { 9454, 33.33 },
            },
        },
        {
            name = "Electrocutioner 6000",
            loot = {
                { 9446, 33.33 },
                { 9447, 33.33 },
                { 9448, 33.33 },
                { 9327, 1 },
                { 6893, 100 },
            },
        },
        {
            name = "Crowd Pummeler 9-60",
            loot = {
                { 9449, 50 },
                { 9450, 50 },
                { 9327, 1 },
            },
        },
        {
            name = "Dark Iron Ambassador",
            loot = {
                { 9455, 33.33 },
                { 9456, 33.33 },
                { 9457, 33.33 },
                { 9308, 15 },
            },
        },
        {
            name = "Mekgineer Thermaplugg",
            loot = {
                { 9458, 25 },
                { 9459, 25 },
                { 9461, 25 },
                { 9492, 25 },
                { 4415, 2 },
                { 4411, 2 },
                { 4413, 2 },
                { 9327, 1 },
                { 7742, 2 },
            },
        },
    },
    notable = {
        trash = {
            { 9508, 0.6, { "Holdout Technician" } },
            { 9326, 35, { "Dark Iron Agent" } },
        },
        objects = {
        },
    },
})
