-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "Maraudon",
    name = "Maraudon",
    kind = "dungeon",
    levels = { 46, 55 },
    bosses = {
        {
            name = "Noxxion",
            loot = {
                { 17744, 33.33 },
                { 17745, 33.33 },
                { 17746, 33.33 },
            },
        },
        {
            name = "Razorlash",
            loot = {
                { 17748, 25 },
                { 17749, 25 },
                { 17750, 25 },
                { 17751, 25 },
                { 22529, 54 },
                { 17747, 6 },
            },
        },
        {
            name = "Lord Vyletongue",
            loot = {
                { 17752, 33.33 },
                { 17754, 33.33 },
                { 17755, 33.33 },
            },
        },
        {
            name = "Celebras the Cursed",
            loot = {
                { 17738, 33.33 },
                { 17739, 33.33 },
                { 17740, 33.33 },
            },
        },
        {
            name = "Landslide",
            loot = {
                { 17734, 25 },
                { 17736, 25 },
                { 17737, 25 },
                { 17943, 25 },
            },
        },
        {
            name = "Tinkerer Gizlock",
            loot = {
                { 17717, 33.33 },
                { 17718, 33.33 },
                { 17719, 33.33 },
                { 10561, 2.15 },
            },
        },
        {
            name = "Rotgrip",
            loot = {
                { 17728, 33.33 },
                { 17730, 33.33 },
                { 17732, 33.33 },
            },
        },
        {
            name = "Princess Theradras",
            loot = {
                { 17780, 1 },
                { 17707, 14.29 },
                { 17710, 14.29 },
                { 17711, 14.29 },
                { 17713, 14.29 },
                { 17714, 14.29 },
                { 17715, 14.29 },
                { 17766, 14.29 },
            },
        },
    },
    notable = {
        trash = {
            { 17741, 33.33, { "Meshlok the Harvester" } },
            { 17742, 33.33, { "Meshlok the Harvester" } },
            { 17767, 33.33, { "Meshlok the Harvester" } },
        },
        objects = {
        },
    },
})
