-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "OnyxiasLair",
    name = "Onyxia's Lair",
    kind = "raid",
    levels = { 60, 60 },
    bosses = {
        {
            name = "Onyxia",
            loot = {
                { 18422, 100 },
                { 18423, 100 },
                { 18705, 40 },
                { 17067, 25 },
                { 17078, 25 },
                { 18205, 25 },
                { 18813, 25 },
                { 16900, 12.5 },
                { 16908, 12.5 },
                { 16914, 12.5 },
                { 16921, 12.5 },
                { 16929, 12.5 },
                { 16939, 12.5 },
                { 16947, 12.5 },
                { 16955, 12.5 },
                { 16963, 12.5 },
                { 17064, 8 },
                { 17068, 8 },
                { 17075, 8 },
                { 17966, 100 },
            },
        },
    },
    notable = {
        trash = {
        },
        objects = {
        },
    },
})
