-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "RagefireChasm",
    name = "Ragefire Chasm",
    kind = "dungeon",
    levels = { 13, 18 },
    bosses = {
        {
            name = "Oggleflint",
            loot = {
                { 3311, 0.07 },
            },
        },
        {
            name = "Taragaman the Hungerer",
            loot = {
                { 14145, 33.33 },
                { 14148, 33.33 },
                { 14149, 33.33 },
            },
        },
        {
            name = "Jergosh the Invoker",
            loot = {
                { 14147, 33.33 },
                { 14150, 33.33 },
                { 14151, 33.33 },
            },
        },
        {
            name = "Bazzalan",
            loot = {
                { 3311, 0.21 },
            },
        },
    },
    notable = {
        trash = {
        },
        objects = {
        },
    },
})
