-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "RazorfenDowns",
    name = "Razorfen Downs",
    kind = "dungeon",
    levels = { 37, 46 },
    bosses = {
        {
            name = "Tuten'kash",
            loot = {
                { 10775, 33.33 },
                { 10776, 33.33 },
                { 10777, 33.33 },
            },
        },
        {
            name = "Plaguemaw the Rotting",
            loot = {
                { 10766, 50 },
                { 10760, 50 },
            },
        },
        {
            name = "Mordresh Fire Eye",
            loot = {
                { 10769, 33.33 },
                { 10770, 33.33 },
                { 10771, 33.33 },
            },
        },
        {
            name = "Glutton",
            loot = {
                { 10774, 50 },
                { 10772, 50 },
            },
        },
        {
            name = "Amnennar the Coldbringer",
            loot = {
                { 10761, 20 },
                { 10762, 20 },
                { 10763, 20 },
                { 10764, 20 },
                { 10765, 20 },
            },
        },
    },
    notable = {
        trash = {
            { 23177, 50, { "Lady Falther'ess" } },
            { 23178, 50, { "Lady Falther'ess" } },
            { 10758, 33.33, { "Ragglesnout" } },
            { 10767, 33.33, { "Ragglesnout" } },
            { 10768, 33.33, { "Ragglesnout" } },
        },
        objects = {
        },
    },
})
