-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "RazorfenKraul",
    name = "Razorfen Kraul",
    kind = "dungeon",
    levels = { 29, 38 },
    bosses = {
        {
            name = "Roogug",
            loot = {
                { 1727, 0.16 },
                { 4438, 0.16 },
                { 1488, 0.08 },
                { 1976, 0.08 },
                { 2264, 0.03 },
            },
        },
        {
            name = "Aggem Thorncurse",
            loot = {
                { 6681, 100 },
            },
        },
        {
            name = "Death Speaker Jargba",
            loot = {
                { 2816, 33.33 },
                { 6682, 33.33 },
                { 6685, 33.33 },
            },
        },
        {
            name = "Overlord Ramtusk",
            loot = {
                { 6687, 50 },
                { 6686, 50 },
            },
        },
        {
            name = "Agathelos the Raging",
            loot = {
                { 6691, 50 },
                { 6690, 50 },
                { 3172, 35 },
                { 2677, 30 },
            },
        },
        {
            name = "Charlga Razorflank",
            loot = {
                { 6692, 33.33 },
                { 6693, 33.33 },
                { 6694, 33.33 },
                { 17008, 100 },
            },
        },
    },
    notable = {
        trash = {
            { 6689, 50, { "Earthcaller Halmgar" } },
            { 6695, 33.33, { "Blind Hunter" } },
            { 6696, 33.33, { "Blind Hunter" } },
            { 6697, 33.33, { "Blind Hunter" } },
        },
        objects = {
        },
    },
})
