-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "ScarletMonastery",
    name = "Scarlet Monastery",
    kind = "dungeon",
    levels = { 26, 45 },
    bosses = {
        {
            name = "Interrogator Vishas",
            wing = "Graveyard",
            loot = {
                { 7682, 50 },
                { 7683, 50 },
            },
        },
        {
            name = "Bloodmage Thalnos",
            wing = "Graveyard",
            loot = {
                { 7685, 50 },
                { 7684, 50 },
            },
        },
        {
            name = "Houndmaster Loksey",
            wing = "Library",
            loot = {
                { 7710, 33.33 },
                { 3456, 33.33 },
                { 7756, 33.33 },
            },
        },
        {
            name = "Arcanist Doan",
            wing = "Library",
            loot = {
                { 7713, 25 },
                { 7714, 25 },
                { 7711, 25 },
                { 7712, 25 },
            },
        },
        {
            name = "Herod",
            wing = "Armory",
            loot = {
                { 7717, 25 },
                { 7718, 25 },
                { 7719, 25 },
                { 10330, 25 },
            },
        },
        {
            name = "High Inquisitor Fairbanks",
            wing = "Cathedral",
            loot = {
                { 19507, 33.33 },
                { 19508, 33.33 },
                { 19509, 33.33 },
            },
        },
        {
            name = "Scarlet Commander Mograine",
            wing = "Cathedral",
            loot = {
                { 7723, 25 },
                { 7724, 25 },
                { 7726, 25 },
                { 10330, 25 },
            },
        },
        {
            name = "High Inquisitor Whitemane",
            wing = "Cathedral",
            loot = {
                { 7720, 33.33 },
                { 7721, 33.33 },
                { 7722, 33.33 },
            },
        },
    },
    notable = {
        trash = {
            { 7686, 33.33, { "Ironspine" } },
            { 7687, 33.33, { "Ironspine" } },
            { 7688, 33.33, { "Ironspine" } },
            { 7689, 33.33, { "Fallen Champion" } },
            { 7690, 33.33, { "Fallen Champion" } },
            { 7691, 33.33, { "Fallen Champion" } },
            { 7708, 33.33, { "Azshir the Sleepless" } },
            { 7709, 33.33, { "Azshir the Sleepless" } },
            { 7731, 33.33, { "Azshir the Sleepless" } },
        },
        objects = {
            { 7146, 100, { "Doan's Strongbox" } },
        },
    },
})
