-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "ShadowfangKeep",
    name = "Shadowfang Keep",
    kind = "dungeon",
    levels = { 22, 30 },
    bosses = {
        {
            name = "Rethilgore",
            loot = {
                { 5254, 100 },
            },
        },
        {
            name = "Razorclaw the Butcher",
            loot = {
                { 1292, 33.33 },
                { 6226, 33.33 },
                { 6633, 33.33 },
            },
        },
        {
            name = "Baron Silverlaine",
            loot = {
                { 6321, 50 },
                { 6323, 50 },
            },
        },
        {
            name = "Commander Springvale",
            loot = {
                { 6320, 50 },
                { 3191, 50 },
            },
        },
        {
            name = "Odo the Blindwatcher",
            loot = {
                { 6318, 50 },
                { 6319, 50 },
            },
        },
        {
            name = "Fenrus the Devourer",
            loot = {
                { 3230, 50 },
                { 6340, 50 },
            },
        },
        {
            name = "Wolf Master Nandos",
            loot = {
                { 3748, 50 },
                { 6314, 50 },
            },
        },
        {
            name = "Archmage Arugal",
            loot = {
                { 6220, 33.33 },
                { 6324, 33.33 },
                { 6392, 33.33 },
            },
        },
    },
    notable = {
        trash = {
            { 6642, 50, { "Deathsworn Captain" } },
            { 23171, 50, { "Sever" } },
            { 23173, 50, { "Sever" } },
        },
        objects = {
        },
    },
})
