-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "TheDeadmines",
    name = "The Deadmines",
    kind = "dungeon",
    levels = { 17, 26 },
    bosses = {
        {
            name = "Rhahk'Zor",
            loot = {
                { 872, 5 },
                { 5187, 95 },
            },
        },
        {
            name = "Sneed's Shredder",
            loot = {
                { 1937, 10 },
                { 2169, 90 },
            },
        },
        {
            name = "Sneed",
            loot = {
                { 5194, 35 },
                { 5195, 65 },
            },
        },
        {
            name = "Gilnid",
            loot = {
                { 1156, 45 },
                { 5199, 55 },
            },
        },
        {
            name = "Mr. Smite",
            loot = {
                { 7230, 20 },
                { 5192, 40 },
                { 5196, 40 },
            },
        },
        {
            name = "Captain Greenskin",
            loot = {
                { 5201, 40 },
                { 5200, 30 },
                { 10403, 30 },
            },
        },
        {
            name = "Edwin VanCleef",
            loot = {
                { 5193, 30 },
                { 5202, 30 },
                { 5191, 20 },
                { 10399, 20 },
                { 2874, 100 },
            },
        },
        {
            name = "Cookie",
            loot = {
                { 5198, 35 },
                { 5197, 65 },
                { 8490, 15 },
            },
        },
    },
    notable = {
        trash = {
            { 5443, 35, { "Miner Johnson" } },
            { 5787, 2.1, { "Defias Pirate" } },
            { 5786, 1.03, { "Defias Squallshaper" } },
        },
        objects = {
            { 5397, 100, { "Defias Gunpowder" } },
        },
    },
})
