-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "TheStockade",
    name = "The Stockade",
    kind = "dungeon",
    levels = { 24, 31 },
    bosses = {
        {
            name = "Targorr the Dread",
            loot = {
            },
        },
        {
            name = "Kam Deepfury",
            loot = {
                { 2280, 1 },
            },
        },
        {
            name = "Hamhock",
            loot = {
            },
        },
        {
            name = "Bazil Thredd",
            loot = {
            },
        },
        {
            name = "Dextren Ward",
            loot = {
            },
        },
        {
            name = "Bruegal Ironknuckle",
            loot = {
                { 2941, 33.33 },
                { 2942, 33.33 },
                { 3228, 33.33 },
            },
        },
    },
    notable = {
        trash = {
        },
        objects = {
        },
    },
})
