-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "TheStockade",
    name = "The Stockade",
    kind = "dungeon",
    levels = { 24, 31 },
    bosses = {
        {
            name = "Targorr the Dread",
            loot = {
                { 2589, 12 },
                { 2592, 12 },
                { 4306, 12 },
                { 929, 1.25 },
                { 3358, 1.25 },
                { 1478, 0.2 },
                { 1711, 0.2 },
                { 1712, 0.2 },
                { 2289, 0.2 },
                { 2290, 0.2 },
            },
        },
        {
            name = "Kam Deepfury",
            loot = {
                { 2280, 1 },
                { 2592, 21.5 },
                { 4306, 21.5 },
                { 1205, 5 },
                { 4542, 5 },
                { 929, 1.25 },
                { 3385, 1.25 },
                { 1478, 0.2 },
                { 1711, 0.2 },
                { 1712, 0.2 },
                { 2289, 0.2 },
                { 2290, 0.2 },
            },
        },
        {
            name = "Hamhock",
            loot = {
            },
        },
        {
            name = "Bazil Thredd",
            loot = {
            },
        },
        {
            name = "Dextren Ward",
            loot = {
                { 2592, 18.5 },
                { 4306, 18.5 },
                { 1478, 0.2 },
                { 1711, 0.2 },
                { 1712, 0.2 },
                { 2289, 0.2 },
                { 2290, 0.2 },
            },
        },
        {
            name = "Bruegal Ironknuckle",
            loot = {
                { 2941, 33.33 },
                { 2942, 33.33 },
                { 3228, 33.33 },
            },
        },
    },
    notable = {
        trash = {
        },
        objects = {
        },
    },
})
