-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "TheTempleOfAtalHakkar",
    name = "The Temple of Atal'Hakkar",
    kind = "dungeon",
    levels = { 50, 56 },
    bosses = {
        {
            name = "Atal'alarion",
            loot = {
                { 10798, 33.33 },
                { 10799, 33.33 },
                { 10800, 33.33 },
                { 8152, 7 },
            },
        },
        {
            name = "Dreamscythe",
            loot = {
                { 10795, 5 },
                { 10796, 5 },
                { 10797, 5 },
                { 12243, 5 },
                { 12463, 5 },
                { 12464, 5 },
                { 12465, 5 },
                { 12466, 5 },
            },
        },
        {
            name = "Weaver",
            loot = {
                { 10795, 5 },
                { 10796, 5 },
                { 10797, 5 },
                { 12243, 5 },
                { 12463, 5 },
                { 12464, 5 },
                { 12465, 5 },
                { 12466, 5 },
            },
        },
        {
            name = "Jammal'an the Prophet",
            loot = {
                { 10806, 33.33 },
                { 10807, 33.33 },
                { 10808, 33.33 },
                { 8152, 7 },
            },
        },
        {
            name = "Ogom the Wretched",
            loot = {
                { 10803, 33.33 },
                { 10804, 33.33 },
                { 10805, 33.33 },
                { 8152, 7 },
            },
        },
        {
            name = "Morphaz",
            loot = {
                { 10795, 5 },
                { 10796, 5 },
                { 10797, 5 },
                { 12243, 5 },
                { 12463, 5 },
                { 12464, 5 },
                { 12465, 5 },
                { 12466, 5 },
            },
        },
        {
            name = "Hazzas",
            loot = {
                { 10795, 5 },
                { 10796, 5 },
                { 10797, 5 },
                { 12243, 5 },
                { 12463, 5 },
                { 12464, 5 },
                { 12465, 5 },
                { 12466, 5 },
            },
        },
        {
            name = "Shade of Eranikus",
            loot = {
                { 10847, 0.5 },
                { 10828, 16.67 },
                { 10829, 16.67 },
                { 10833, 16.67 },
                { 10835, 16.67 },
                { 10836, 16.67 },
                { 10837, 16.67 },
                { 10454, 100 },
            },
        },
        {
            name = "Avatar of Hakkar",
            loot = {
                { 12462, 2 },
                { 10838, 16.67 },
                { 10842, 16.67 },
                { 10843, 16.67 },
                { 10844, 16.67 },
                { 10845, 16.67 },
                { 10846, 16.67 },
            },
        },
    },
    notable = {
        trash = {
            { 10801, 47.43, { "Spawn of Hakkar" } },
            { 10783, 6.67, { "Gasher", "Hukku", "Loro" } },
            { 10784, 6.67, { "Gasher", "Hukku", "Loro" } },
            { 10787, 6.67, { "Gasher", "Hukku", "Loro" } },
            { 15733, 3.64, { "Murk Worm" } },
            { 16216, 1.48, { "Atal'ai Witch Doctor" } },
        },
        objects = {
        },
    },
})
