-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "Uldaman",
    name = "Uldaman",
    kind = "dungeon",
    levels = { 41, 51 },
    bosses = {
        {
            name = "Revelosh",
            loot = {
                { 9387, 25 },
                { 9388, 25 },
                { 9389, 25 },
                { 9390, 25 },
                { 7741, 100 },
            },
        },
        {
            name = "The Lost Dwarves",
            loot = {
                { 9394, 50 },
                { 9401, 50 },
                { 9404, 50 },
                { 9399, 100 },
                { 9398, 50 },
                { 1177, 100 },
                { 2459, 100 },
                { 9400, 50 },
                { 9403, 50 },
                { 2304, 25 },
                { 2313, 25 },
                { 4265, 25 },
                { 8173, 25 },
            },
        },
        {
            name = "Ironaya",
            loot = {
                { 9407, 33.33 },
                { 9408, 33.33 },
                { 9409, 33.33 },
            },
        },
        {
            name = "Obsidian Sentinel",
            loot = {
                { 9431, 0.07 },
                { 9426, 0.06 },
                { 9428, 0.03 },
                { 9384, 0.02 },
                { 9393, 0.02 },
                { 9396, 0.02 },
                { 9420, 0.02 },
                { 9424, 0.02 },
                { 9425, 0.02 },
                { 9427, 0.02 },
                { 5833, 0.16 },
            },
        },
        {
            name = "Ancient Stone Keeper",
            loot = {
                { 9410, 50 },
                { 9411, 50 },
            },
        },
        {
            name = "Galgann Firehammer",
            loot = {
                { 9412, 25 },
                { 11310, 25 },
                { 9419, 25 },
                { 11311, 25 },
            },
        },
        {
            name = "Grimlok",
            loot = {
                { 9415, 33.33 },
                { 9416, 33.33 },
                { 9414, 33.33 },
            },
        },
        {
            name = "Archaedas",
            loot = {
                { 9413, 33.33 },
                { 9418, 33.33 },
                { 11118, 33.33 },
            },
        },
    },
    notable = {
        trash = {
            { 7666, 12, { "Stonevault Oracle", "Stonevault Rockchewer" } },
        },
        objects = {
        },
    },
})
