-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "WailingCaverns",
    name = "Wailing Caverns",
    kind = "dungeon",
    levels = { 17, 24 },
    bosses = {
        {
            name = "Lady Anacondra",
            loot = {
                { 10412, 33.33 },
                { 5404, 33.33 },
                { 6446, 33.33 },
            },
        },
        {
            name = "Lord Cobrahn",
            loot = {
                { 6460, 33.33 },
                { 10410, 33.33 },
                { 6465, 33.33 },
            },
        },
        {
            name = "Kresh",
            loot = {
                { 13245, 50 },
                { 6447, 50 },
                { 6470, 6 },
                { 6471, 2 },
            },
        },
        {
            name = "Lord Pythas",
            loot = {
                { 6472, 50 },
                { 6473, 50 },
            },
        },
        {
            name = "Skum",
            loot = {
                { 6449, 50 },
                { 6448, 50 },
                { 5470, 20 },
                { 6470, 6 },
                { 6471, 2 },
            },
        },
        {
            name = "Lord Serpentis",
            loot = {
                { 6469, 25 },
                { 5970, 25 },
                { 6459, 25 },
                { 10411, 25 },
            },
        },
        {
            name = "Verdan the Everliving",
            loot = {
                { 6630, 33.33 },
                { 6631, 33.33 },
                { 6629, 33.33 },
                { 6470, 6 },
                { 765, 2 },
                { 785, 2 },
                { 2447, 2 },
                { 2449, 2 },
                { 2450, 2 },
                { 2452, 2 },
                { 2453, 2 },
                { 6471, 2 },
            },
        },
        {
            name = "Mutanus the Devourer",
            loot = {
                { 6461, 33.33 },
                { 6463, 33.33 },
                { 6627, 33.33 },
                { 10441, 100 },
                { 6470, 6 },
                { 6471, 2 },
            },
        },
    },
    notable = {
        trash = {
            { 5243, 50, { "Deviate Faerie Dragon" } },
        },
        objects = {
        },
    },
})
