-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.
local _, ns = ...

ns.AddInstance({
    key = "ZulFarrak",
    name = "Zul'Farrak",
    kind = "dungeon",
    levels = { 44, 54 },
    bosses = {
        {
            name = "Antu'sul",
            loot = {
                { 9379, 25 },
                { 9639, 25 },
                { 9640, 25 },
                { 9641, 25 },
                { 9484, 0.01 },
                { 9243, 2 },
            },
        },
        {
            name = "Theka the Martyr",
            loot = {
                { 862, 0.02 },
                { 2040, 0.02 },
                { 5616, 0.02 },
                { 9480, 0.02 },
                { 9481, 0.02 },
                { 9482, 0.02 },
                { 9483, 0.02 },
                { 9511, 0.02 },
                { 9512, 0.02 },
                { 8623, 0.6 },
                { 9243, 0.56 },
            },
        },
        {
            name = "Witch Doctor Zum'rah",
            loot = {
                { 18082, 50 },
                { 18083, 50 },
                { 9243, 2 },
            },
        },
        {
            name = "Nekrum Gutchewer",
            loot = {
                { 9480, 0.1 },
                { 9482, 0.02 },
                { 9511, 0.02 },
                { 8623, 2 },
                { 9243, 0.64 },
            },
        },
        {
            name = "Shadowpriest Sezz'ziz",
            loot = {
                { 9470, 25 },
                { 9473, 25 },
                { 9474, 25 },
                { 9475, 25 },
                { 9243, 2 },
            },
        },
        {
            name = "Sergeant Bly",
            loot = {
                { 5616, 0.02 },
                { 9482, 0.02 },
                { 8623, 0.5 },
            },
        },
        {
            name = "Hydromancer Velratha",
            loot = {
                { 862, 0.02 },
                { 5616, 0.02 },
                { 9481, 0.02 },
                { 9483, 0.02 },
                { 9512, 0.02 },
                { 8623, 0.7 },
                { 9243, 0.7 },
            },
        },
        {
            name = "Gahz'rilla",
            loot = {
                { 9469, 50 },
                { 9467, 50 },
            },
        },
        {
            name = "Chief Ukorz Sandscalp",
            loot = {
                { 9476, 20 },
                { 9477, 20 },
                { 9478, 20 },
                { 9479, 20 },
                { 11086, 20 },
                { 9484, 0.01 },
                { 9243, 2 },
            },
        },
        {
            name = "Ruuzlu",
            loot = {
                { 9511, 0.08 },
                { 6440, 0.05 },
                { 5616, 0.04 },
                { 862, 0.03 },
                { 9481, 0.03 },
                { 9512, 0.03 },
                { 9243, 0.98 },
                { 8623, 0.9 },
            },
        },
    },
    notable = {
        trash = {
            { 12470, 18.69, { "Zerillis" } },
            { 8623, 2, { "Zerillis", "Scarab", "Oro Eyegouge" } },
        },
        objects = {
        },
    },
})
