import { test } from 'node:test';
import assert from 'node:assert/strict';
import { luaString, raresFile, spawnsFile } from '../lib/lua.mjs';

test('strings are quoted and escaped for Lua', () => {
  assert.equal(luaString('Ol\' "Blue" \\ x'), '"Ol\' \\"Blue\\" \\\\ x"');
});

test('the rares file hands every rare to ns.AddRares: name, levels, elite', () => {
  const text = raresFile([
    { entry: 462, name: 'Vultros', minLevel: 26, maxLevel: 26, elite: false },
    { entry: 1, name: 'Elite "One"', minLevel: 40, maxLevel: 42, elite: true },
  ]);
  assert.match(text, /^-- Generated by tools\/build-data\.mjs/);
  assert.match(text, /local _, ns = \.\.\./);
  assert.match(text, /ns\.AddRares\(\{/);
  assert.match(text, /\[462\] = \{ "Vultros", 26, 26, false \},/);
  assert.match(text, /\[1\] = \{ "Elite \\"One\\"", 40, 42, true \},/);
});

test('a spawns file hands a continent its flat list: id, x, y, ...', () => {
  const text = spawnsFile(0, [{ entry: 462, x: -10603.8, y: 1154.1 }, { entry: 1, x: 3, y: 4 }]);
  assert.match(text, /ns\.AddSpawns\(0, \{/);
  assert.match(text, /462, -10603\.8, 1154\.1,/);
  assert.match(text, /1, 3, 4,/);
});
