import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { readRecordings, recordedFile, toLua } from '../lib/recordings.mjs';

const saved = (recorder, count) => [
  'RareMobDB = {',
  `\t["recorder"] = "${recorder}",`,
  '\t["settings"] = { ["alert"] = true },',
  '\t["sightings"] = {',
  '\t\t[462] = {',
  '\t\t\t["name"] = "Vultros",',
  '\t\t\t["level"] = 26,',
  '\t\t\t["elite"] = false,',
  `\t\t\t["count"] = ${count},`,
  '\t\t\t["last"] = 1790000500,',
  '\t\t\t["note"] = "dropped",',
  '\t\t\t["places"] = {',
  '\t\t\t\t{ ["map"] = 1436, ["x"] = 0.5, ["y"] = 0.25, ["time"] = 1790000500 }, -- [1]',
  '\t\t\t\t{ ["map"] = 1436, ["x"] = "bad" }, -- [2]',
  '\t\t\t},',
  '\t\t},',
  '\t\t["junk"] = 5,',
  '\t},',
  '}',
].join('\n');

function files(contents) {
  const dir = mkdtempSync(join(tmpdir(), 'raremob-'));
  return Object.entries(contents).map(([name, text]) => {
    const path = join(dir, name);
    writeFileSync(path, text);
    return path;
  });
}

test("reads each recorder's sightings, keeping only what RareMob uses", () => {
  const { recordings, warnings } = readRecordings(files({ 'a.lua': saved('aaaa', 3), 'b.lua': saved('bbbb', 1) }));
  assert.deepEqual(warnings, []);
  assert.deepEqual(recordings.map((r) => r.recorder), ['aaaa', 'bbbb']);
  assert.deepEqual(recordings[0].sightings, {
    462: {
      name: 'Vultros', level: 26, elite: false, count: 3, last: 1790000500,
      places: [{ map: 1436, x: 0.5, y: 0.25, time: 1790000500 }],
    },
  });
});

test('skips a file without a recorder, and one it cannot read, and says so', () => {
  const { recordings, warnings } = readRecordings(files({ 'old.lua': 'RareMobDB = { ["settings"] = {} }', 'bad.lua': 'X = {' }));
  assert.equal(recordings.length, 0);
  assert.equal(warnings.length, 2);
});

test('keeps the later file when one recorder was sent twice', () => {
  const { recordings } = readRecordings(files({ '1-old.lua': saved('aaaa', 1), '2-new.lua': saved('aaaa', 9) }));
  assert.equal(recordings.length, 1);
  assert.equal(recordings[0].sightings[462].count, 9);
});

test('writes Lua: numeric keys, names, lists', () => {
  assert.equal(toLua({ 462: 2, name: 'x' }), '{\n    [462] = 2,\n    name = "x",\n}');
  assert.equal(toLua([1, 2]), '{\n    1,\n    2,\n}');
  assert.equal(toLua({}), '{}');
});

test('the recorded file hands each recorder to ns.AddRecordings', () => {
  const { recordings } = readRecordings(files({ 'a.lua': saved('aaaa', 3) }));
  const text = recordedFile(recordings);
  assert.match(text, /^-- Generated by tools\/bake-recordings\.mjs/);
  assert.match(text, /ns\.AddRecordings\("aaaa", \{/);
  assert.match(text, /\[462\] = \{/);
  assert.match(text, /name = "Vultros",/);
  assert.match(recordedFile([]), /local _, ns = \.\.\./);
});
