// Writing GatherMap's generated Lua data files.
import { luaString } from '../../../BossLoot/tools/lib/lua.mjs';

const HEADER = '-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.';

// Lua 5.1 allows 262143 constants in one chunk; a file of 5000 spawns holds
// at most 15000, far under it, and the client loads each quickly.
export const SPAWNS_PER_FILE = 5000;
export const CONTINENT_FILES = { 0: 'EasternKingdoms', 1: 'Kalimdor' };

export function nodesFile(nodes) {
  const lines = [HEADER, 'local _, ns = ...', '', 'ns.AddNodes({'];
  for (const node of nodes) {
    const fields = [`kind = ${luaString(node.kind)}`, `name = ${luaString(node.name)}`];
    if (node.skill !== undefined) fields.push(`skill = ${node.skill}`);
    if (node.item !== undefined) fields.push(`item = ${node.item}`);
    lines.push(`    [${node.entry}] = { ${fields.join(', ')} },`);
  }
  lines.push('})', '');
  return lines.join('\n');
}

export function spawnFiles(byContinent) {
  const files = [];
  for (const [continent, list] of byContinent) {
    for (let start = 0, part = 1; start < list.length; start += SPAWNS_PER_FILE, part++) {
      const lines = [HEADER, 'local _, ns = ...', '', `ns.AddSpawns(${continent}, {`];
      const chunk = list.slice(start, start + SPAWNS_PER_FILE);
      for (let i = 0; i < chunk.length; i += 10) {
        lines.push(`    ${chunk.slice(i, i + 10).map((s) => `${s.entry}, ${s.x}, ${s.y},`).join(' ')}`);
      }
      lines.push('})', '');
      files.push({ file: `${CONTINENT_FILES[continent]}${part}.lua`, text: lines.join('\n') });
    }
  }
  return files;
}

export function confirmedFile(keys) {
  const lines = [HEADER, '-- Spawns players have gathered in WoW Forever, from tools/recordings/.', 'local _, ns = ...', '', 'ns.AddConfirmed({'];
  for (const key of keys) lines.push(`    ${luaString(key)},`);
  lines.push('})', '');
  return lines.join('\n');
}
