// Writing the generated Lua data files.

const HEADER = '-- Generated by tools/build-data.mjs from the vMaNGOS world database. Do not edit.';

export function luaString(value) {
  return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
}

/** Data/Rares.lua: every rare by id, { name, minLevel, maxLevel, elite }. */
export function raresFile(rares) {
  const lines = [
    HEADER,
    '-- Every rare and rare elite: name, lowest level, highest level, elite.',
    'local _, ns = ...',
    '',
    'ns.AddRares({',
  ];
  for (const rare of rares) {
    lines.push(`    [${rare.entry}] = { ${luaString(rare.name)}, ${rare.minLevel}, ${rare.maxLevel}, ${rare.elite} },`);
  }
  lines.push('})', '');
  return lines.join('\n');
}

/** Data/Spawns<Continent>.lua: one continent's spawns, flat: id, x, y, ... in world yards. */
export function spawnsFile(continent, spawns) {
  const lines = [
    HEADER,
    '-- Where each rare spawns: creature id, world x, world y, in turn.',
    'local _, ns = ...',
    '',
    `ns.AddSpawns(${continent}, {`,
  ];
  for (const spawn of spawns) lines.push(`    ${spawn.entry}, ${spawn.x}, ${spawn.y},`);
  lines.push('})', '');
  return lines.join('\n');
}
