// Sightings players made in WoW Forever, from their saved-variables files
// (WTF/Account/<name>/SavedVariables/RareMob.lua), baked into
// Data/Recorded.lua one recorder at a time. The addon leaves out the baked
// copy of the player's own recorder, so a player's sightings never count
// twice.

import { readFileSync } from 'node:fs';
import { basename } from 'node:path';
import { parseSavedVariables } from './savedvars.mjs';
import { luaString } from './lua.mjs';

const PLACES_KEPT = 20;

const isNumber = (value) => typeof value === 'number' && Number.isFinite(value);

// The parser gives a Lua list as an object keyed "1", "2", ...
const listOf = (value) => (value && typeof value === 'object' ? Object.values(value) : []);

/** One sighting as RareMob saves it, cut down to what it reads; nil if unusable. */
function cleanSighting(sighting) {
  if (!sighting || typeof sighting !== 'object' || typeof sighting.name !== 'string') return undefined;
  const places = listOf(sighting.places)
    .filter((place) => place && isNumber(place.map) && isNumber(place.x) && isNumber(place.y) && isNumber(place.time))
    .map((place) => ({ map: place.map, x: place.x, y: place.y, time: place.time }))
    .slice(-PLACES_KEPT);
  return {
    name: sighting.name,
    level: isNumber(sighting.level) ? sighting.level : 0,
    elite: sighting.elite === true,
    count: isNumber(sighting.count) ? sighting.count : 1,
    last: isNumber(sighting.last) ? sighting.last : 0,
    places,
  };
}

/** Each recorder's sightings in the files, in the order given. */
export function readRecordings(files) {
  const byRecorder = new Map();
  const warnings = [];
  for (const file of files) {
    const name = basename(file);
    let vars;
    try {
      vars = parseSavedVariables(readFileSync(file, 'utf8'));
    } catch (error) {
      warnings.push(`${name}: ${error.message}`);
      continue;
    }
    const db = vars.RareMobDB;
    if (!db || typeof db.recorder !== 'string') {
      warnings.push(`${name}: no RareMob recorder`);
      continue;
    }
    const sightings = {};
    for (const [id, sighting] of Object.entries(db.sightings ?? {})) {
      const clean = /^\d+$/.test(id) && cleanSighting(sighting);
      if (clean) sightings[id] = clean;
    }
    // A recorder sent twice: the later file wins.
    byRecorder.set(db.recorder, { recorder: db.recorder, sightings });
  }
  return { recordings: [...byRecorder.values()], warnings };
}

/** A value as Lua source. */
export function toLua(value, indent = '') {
  if (value === null || value === undefined) return 'nil';
  if (typeof value === 'string') return luaString(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  const inner = `${indent}    `;
  if (Array.isArray(value)) {
    if (!value.length) return '{}';
    return `{\n${value.map((each) => `${inner}${toLua(each, inner)},`).join('\n')}\n${indent}}`;
  }
  const keys = Object.keys(value);
  if (!keys.length) return '{}';
  const lines = keys.map((key) => {
    let written;
    if (/^-?\d+$/.test(key)) written = `[${key}]`;
    else if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) written = key;
    else written = `[${luaString(key)}]`;
    return `${inner}${written} = ${toLua(value[key], inner)},`;
  });
  return `{\n${lines.join('\n')}\n${indent}}`;
}

/** Data/Recorded.lua: each recorder's sightings handed to ns.AddRecordings. */
export function recordedFile(recordings) {
  const lines = [
    '-- Generated by tools/bake-recordings.mjs from RareMob saved variables. Do not edit.',
    '-- Rares seen in WoW Forever, by recorder.',
    'local _, ns = ...',
    '',
  ];
  for (const { recorder, sightings } of recordings) {
    lines.push(`ns.AddRecordings(${luaString(recorder)}, ${toLua(sightings)})`, '');
  }
  return lines.join('\n');
}
