local helpers = require("helpers")

describe("the saved variables", function()
    it("start with pins on and nothing gathered", function()
        local ns, env = helpers.loggedIn()
        assertTrue(ns.settings.enabled)
        assertEqual(env.GatherMapSettings, ns.settings)
        assertEqual(env.GatherMapDB, ns.db)
        assertEqual("table", type(ns.db.gathered))
        assertEqual("table", type(ns.db.missing))
    end)

    it("keep what was saved", function()
        local ns = helpers.loggedIn(function(env)
            env.GatherMapSettings = { enabled = false }
            env.GatherMapDB = { gathered = { x = { count = 2 } } }
        end)
        assertFalse(ns.settings.enabled)
        assertEqual(2, ns.db.gathered.x.count)
    end)

    it("replace a saved value that is not a table", function()
        local ns = helpers.loggedIn(function(env) env.GatherMapDB = "broken" end)
        assertEqual("table", type(ns.db.gathered))
    end)
end)

describe("the data files", function()
    it("hand over the catalog and the spawns", function()
        local ns = helpers.loadAddon()
        assertEqual("Copper Vein", ns.Nodes[1731].name)
        assertEqual(1731, ns.rawSpawns[0][1])
        assertEqual(1618, ns.rawSpawns[1][1])
        assertTrue(ns.confirmed["0:3764:-10610.0:1160.0"])
    end)
end)

describe("logging in", function()
    it("runs every login handler, even after one that raises", function()
        local ns, env = helpers.loadAddon()
        local ran = false
        ns.OnLogin(function() error("broken") end)
        ns.OnLogin(function() ran = true end)
        helpers.login(ns, env)
        assertTrue(ran)
        assertMatch("Loaded%.", helpers.printed(env))
    end)
end)

describe("refreshing", function()
    it("runs every refresher", function()
        local ns = helpers.loggedIn()
        local count = 0
        ns.OnRefresh(function() count = count + 1 end)
        ns.OnRefresh(function() count = count + 10 end)
        ns.Refresh()
        assertEqual(11, count)
    end)

    it("happens when pins are turned off or on", function()
        local ns = helpers.loggedIn()
        local count = 0
        ns.OnRefresh(function() count = count + 1 end)
        ns.SetEnabled(false)
        assertFalse(ns.settings.enabled)
        assertEqual(1, count)
    end)
end)

describe("commands", function()
    it("list themselves for /gmap help", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "help")
        assertMatch("/gmap toggle", helpers.printed(env))
    end)

    it("turn the pins off and on with /gmap toggle, and say so", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "toggle")
        assertFalse(ns.settings.enabled)
        assertMatch("Pins hidden", helpers.printed(env))
        helpers.command(env, "toggle")
        assertTrue(ns.settings.enabled)
        assertMatch("Pins shown", helpers.printed(env))
    end)

    it("name an unknown command and list the rest", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "fly")
        assertMatch("Unknown command: fly", helpers.printed(env))
    end)

    it("answer to /gathermap and /gmap", function()
        local ns, env = helpers.loggedIn()
        assertEqual("/gathermap", env.SLASH_GATHERMAP1)
        assertEqual("/gmap", env.SLASH_GATHERMAP2)
    end)
end)
