local helpers = require("helpers")

describe("the minimap button's geometry", function()
    local ns = helpers.loadAddon()

    it("puts angle 0 to the right and 90 at the top", function()
        local x, y = ns.MinimapButton.PositionFor(0, 80)
        assertNear(80, x)
        assertNear(0, y)
        x, y = ns.MinimapButton.PositionFor(90, 80)
        assertNear(0, x)
        assertNear(80, y)
    end)

    it("turns a cursor offset back into an angle between 0 and 360", function()
        assertNear(0, ns.MinimapButton.AngleFor(10, 0))
        assertNear(90, ns.MinimapButton.AngleFor(0, 10))
        assertNear(225, ns.MinimapButton.AngleFor(-10, -10))
    end)
end)

describe("the minimap button", function()
    it("sits on the minimap at its own angle, with GatherMap's icon", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual(env.Minimap, button:GetParent())
        assertEqual(220, ns.settings.button.angle)
        assertEqual("Interface\\AddOns\\GatherMap\\minimap", button.icon:GetTexture())
    end)

    it("shows and hides every pin on a click, and says which in the tooltip", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnClick(button, "LeftButton")
        assertFalse(ns.settings.enabled)
        button.scripts.OnEnter(button)
        assertMatch("hidden", env.GameTooltip.text)
        button.scripts.OnClick(button, "LeftButton")
        assertTrue(ns.settings.enabled)
        assertMatch("shown", env.GameTooltip.text, "the tooltip under the cursor keeps up")
    end)

    it("opens the settings on a right-click", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual("RightButtonUp", button.clicks[2])
        button.scripts.OnClick(button, "RightButton")
        assertEqual("category-id", env.__openedCategory)
        assertTrue(ns.settings.enabled, "a right-click leaves the pins alone")
    end)

    it("hides and shows with /gmap minimap, and remembers", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "minimap")
        assertFalse(ns.MinimapButton.Button():IsShown())
        assertTrue(ns.settings.button.hide)
        assertMatch("/gmap minimap brings it back", helpers.printed(env))
        helpers.command(env, "minimap")
        assertTrue(ns.MinimapButton.Button():IsShown())
    end)
end)
