import { test } from 'node:test';
import assert from 'node:assert/strict';
import { nodesFile, spawnFiles, SPAWNS_PER_FILE } from '../lib/lua.mjs';

test('the nodes file hands the catalog to ns.AddNodes', () => {
  const text = nodesFile([
    { entry: 1731, kind: 'ore', name: 'Copper Vein', skill: 1, item: 2770 },
    { entry: 2843, kind: 'chest', name: "Buccaneer's \"Box\"" },
  ]);
  assert.match(text, /^-- Generated by tools\/build-data\.mjs/);
  assert.match(text, /ns\.AddNodes\(\{/);
  assert.match(text, /\[1731\] = \{ kind = "ore", name = "Copper Vein", skill = 1, item = 2770 \},/);
  assert.match(text, /\[2843\] = \{ kind = "chest", name = "Buccaneer's \\"Box\\"" \},/);
});

test('spawn files hold flat entry, x, y lists, split so no file is too big for the client', () => {
  const many = Array.from({ length: SPAWNS_PER_FILE + 1 }, (_, i) => ({ entry: 1731, x: i, y: -i }));
  const files = spawnFiles(new Map([[0, many], [1, [{ entry: 1617, x: 1.5, y: 2 }]]]));
  assert.deepEqual(files.map((f) => f.file), ['EasternKingdoms1.lua', 'EasternKingdoms2.lua', 'Kalimdor1.lua']);
  assert.match(files[0].text, /ns\.AddSpawns\(0, \{/);
  assert.match(files[0].text, /1731, 0, 0, 1731, 1, -1,/);
  assert.match(files[2].text, /ns\.AddSpawns\(1, \{\n    1617, 1\.5, 2,\n\}\)/);
});

test('a continent with no spawns writes no file', () => {
  assert.deepEqual(spawnFiles(new Map([[0, []], [1, []]])), []);
});
