import { test } from 'node:test';
import assert from 'node:assert/strict';
import { luaString, instanceFile, updateToc } from '../lib/lua.mjs';

test('strings are quoted and escaped for Lua', () => {
  assert.equal(luaString('Doom\'rel "the" \\ x'), '"Doom\'rel \\"the\\" \\\\ x"');
});

test('an instance file hands its instance to ns.AddInstance', () => {
  const text = instanceFile({
    key: 'Test', name: 'Test Depths', kind: 'dungeon', levels: [52, 60],
    bosses: [{ name: 'Boss One', wing: 'East', loot: [{ id: 100, chance: 0.3 }] }],
    notable: { trash: [{ id: 103, chance: 2, sources: ['Trash Mob'] }], objects: [] },
  });
  assert.match(text, /^-- Generated by tools\/build-data\.mjs/);
  assert.match(text, /ns\.AddInstance\(\{/);
  assert.match(text, /wing = "East",/);
  assert.match(text, /\{ 100, 0\.3 \},/);
  assert.match(text, /\{ 103, 2, \{ "Trash Mob" \} \},/);
});

test('the TOC gets the data files between its markers, and nothing else changes', () => {
  const toc = ['## Title: BossLoot', 'BossLoot.lua', '# BEGIN GENERATED DATA', 'Data\\Old.lua', '# END GENERATED DATA', 'Index.lua'].join('\n');
  assert.equal(
    updateToc(toc, ['A.lua', 'B.lua']),
    ['## Title: BossLoot', 'BossLoot.lua', '# BEGIN GENERATED DATA', 'Data\\A.lua', 'Data\\B.lua', '# END GENERATED DATA', 'Index.lua'].join('\n'),
  );
});

test('a TOC without markers is refused', () => {
  assert.throws(() => updateToc('BossLoot.lua', ['A.lua']), /markers/);
});

test('writes the map, and each boss model and pin', () => {
  const text = instanceFile({
    key: 'Test', name: 'Test Depths', kind: 'dungeon', levels: [52, 60],
    map: { cols: 96, rows: 71, runs: [0, 5, 9] },
    bosses: [{ name: 'Boss One', display: 8807, pin: { x: 0.25, y: 0.5 }, loot: [] }],
    notable: { trash: [], objects: [] },
  });
  assert.match(text, /map = \{ cols = 96, rows = 71, runs = \{\n\s+0, 5, 9,\n\s+\} \},/);
  assert.match(text, /display = 8807,/);
  assert.match(text, /pin = \{ 0\.25, 0\.5 \},/);
});

test('writes the entrance', () => {
  const text = instanceFile({
    key: 'Test', name: 'Test Depths', kind: 'dungeon', levels: [52, 60],
    entrance: { x: 0.1, y: 0.9 }, bosses: [], notable: { trash: [], objects: [] },
  });
  assert.match(text, /entrance = \{ 0\.1, 0\.9 \},/);
});

test('the items file hands every item to ns.AddItems: name, quality, class, subclass, slot', async () => {
  const { itemsFile } = await import('../lib/lua.mjs');
  const text = itemsFile([
    { entry: 9387, name: "Revelosh's Boots", quality: 2, class: 4, subclass: 4, inventory_type: 8 },
    { entry: 11684, name: 'Ironfoe', quality: 4, class: 2, subclass: 4, inventory_type: 21 },
  ]);
  assert.match(text, /^-- Generated by tools\/build-data\.mjs/);
  assert.match(text, /ns\.AddItems\(\{/);
  assert.match(text, /\[9387\] = \{ "Revelosh's Boots", 2, 4, 4, 8 \},/);
  assert.match(text, /\[11684\] = \{ "Ironfoe", 4, 2, 4, 21 \},/);
});

test("writes the map id, and each boss's creatures and chests", () => {
  const text = instanceFile({
    key: 'Test', name: 'Test Depths', kind: 'dungeon', levels: [52, 60], mapID: 230,
    bosses: [{ name: 'Boss One', npcs: [1, 2], loot: [] }, { name: 'Chest', objects: [50], loot: [] }],
    notable: { trash: [], objects: [] },
  });
  assert.match(text, /mapID = 230,/);
  assert.match(text, /npcs = \{ 1, 2 \},/);
  assert.match(text, /objects = \{ 50 \},/);
});
