import { test } from 'node:test';
import assert from 'node:assert/strict';
import { luaString, instanceFile, updateToc } from '../lib/lua.mjs';

test('strings are quoted and escaped for Lua', () => {
  assert.equal(luaString('Doom\'rel "the" \\ x'), '"Doom\'rel \\"the\\" \\\\ x"');
});

test('an instance file hands its instance to ns.AddInstance', () => {
  const text = instanceFile({
    key: 'Test', name: 'Test Depths', kind: 'dungeon', levels: [52, 60],
    bosses: [{ name: 'Boss One', wing: 'East', loot: [{ id: 100, chance: 0.3 }] }],
    notable: { trash: [{ id: 103, chance: 2, sources: ['Trash Mob'] }], objects: [] },
  });
  assert.match(text, /^-- Generated by tools\/build-data\.mjs/);
  assert.match(text, /ns\.AddInstance\(\{/);
  assert.match(text, /wing = "East",/);
  assert.match(text, /\{ 100, 0\.3 \},/);
  assert.match(text, /\{ 103, 2, \{ "Trash Mob" \} \},/);
});

test('the TOC gets the data files between its markers, and nothing else changes', () => {
  const toc = ['## Title: BossLoot', 'BossLoot.lua', '# BEGIN GENERATED DATA', 'Data\\Old.lua', '# END GENERATED DATA', 'Index.lua'].join('\n');
  assert.equal(
    updateToc(toc, ['A.lua', 'B.lua']),
    ['## Title: BossLoot', 'BossLoot.lua', '# BEGIN GENERATED DATA', 'Data\\A.lua', 'Data\\B.lua', '# END GENERATED DATA', 'Index.lua'].join('\n'),
  );
});

test('a TOC without markers is refused', () => {
  assert.throws(() => updateToc('BossLoot.lua', ['A.lua']), /markers/);
});
