import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { readRecordings, recordedFile, toLua } from '../lib/recordings.mjs';

const saved = (recorder, kills) => [
  'BossLootDB = {',
  '\t["recorded"] = {',
  `\t\t["recorder"] = "${recorder}",`,
  `\t\t["sources"] = { ["npc:6910"] = { ["kills"] = ${kills}, ["items"] = { [9387] = 1 } } },`,
  '\t\t["seen"] = { "Creature-0-1-70-47-6910-A" },',
  '\t},',
  '}',
].join('\n');

function folder(files) {
  const dir = mkdtempSync(join(tmpdir(), 'recordings-'));
  for (const [name, text] of Object.entries(files)) writeFileSync(join(dir, name), text);
  return dir;
}

test("reads each recorder's recordings, without the corpses seen", () => {
  const { recordings, warnings } = readRecordings(folder({ 'a.lua': saved('aaaa', 5), 'b.lua': saved('bbbb', 2) }));
  assert.deepEqual(warnings, []);
  assert.deepEqual(recordings.map((r) => r.recorder), ['aaaa', 'bbbb']);
  assert.equal(recordings[0].data.sources['npc:6910'].kills, 5);
  assert.equal(recordings[0].data.seen, undefined);
  assert.deepEqual(recordings[0].data.quests, {});
});

test('skips a file without recordings, and says so', () => {
  const { recordings, warnings } = readRecordings(folder({ 'old.lua': 'BossLootDB = { ["view"] = {} }', 'bad.lua': 'X = {' }));
  assert.equal(recordings.length, 0);
  assert.equal(warnings.length, 2);
});

test('keeps the later file when one recorder was sent twice', () => {
  const { recordings } = readRecordings(folder({ '1-old.lua': saved('aaaa', 1), '2-new.lua': saved('aaaa', 9) }));
  assert.equal(recordings.length, 1);
  assert.equal(recordings[0].data.sources['npc:6910'].kills, 9);
});

test('has nothing to read without the folder', () => {
  assert.deepEqual(readRecordings(join(tmpdir(), 'no-such-folder-bossloot')), { recordings: [], warnings: [] });
});

test('writes Lua: numeric keys, names, quoted keys, nesting', () => {
  assert.equal(toLua({ 9387: 2, kills: 5, 'npc:1': 'x' }), '{\n    [9387] = 2,\n    kills = 5,\n    ["npc:1"] = "x",\n}');
  assert.equal(toLua({}), '{}');
});

test('the recorded file hands each recorder to ns.AddRecordings', () => {
  const { recordings } = readRecordings(folder({ 'a.lua': saved('aaaa', 5) }));
  const text = recordedFile(recordings);
  assert.match(text, /^-- Generated by tools\/build-data\.mjs/);
  assert.match(text, /ns\.AddRecordings\("aaaa", \{/);
  assert.match(text, /\["npc:6910"\] = \{/);
  assert.match(recordedFile([]), /local _, ns = \.\.\./);
});
