local helpers = require("helpers")

describe("a map's place in the world", function()
    it("is read from the corners the game reports, and kept", function()
        local ns, env = helpers.loggedIn()
        local rect = ns.Geometry.MapRect(1436)
        assertEqual(0, rect.continent)
        assertEqual(-10000, rect.x0)
        assertEqual(2000, rect.y0)
        assertEqual(-11000, rect.x1)
        assertEqual(1000, rect.y1)
        env.__maps[1436] = nil
        assertTrue(ns.Geometry.MapRect(1436) == rect, "a map's place never moves, so it is asked once")
    end)

    it("is nil for a map the game cannot place, or no map", function()
        local ns = helpers.loggedIn()
        assertNil(ns.Geometry.MapRect(947))
        assertNil(ns.Geometry.MapRect(nil))
    end)

    it("is nil when the client refuses", function()
        local ns, env = helpers.loggedIn()
        env.C_Map.GetWorldPosFromMapPos = function() error("secret") end
        assertNil(ns.Geometry.MapRect(1436))
    end)
end)

describe("a world position on a map", function()
    it("runs across with world Y and down with world X", function()
        local ns = helpers.loggedIn()
        local x, y = ns.Geometry.ToMap(ns.Geometry.MapRect(1436), -10603.8, 1154.0)
        assertNear(0.846, x)
        assertNear(0.6038, y)
    end)

    it("agrees with where the game puts the player", function()
        local ns, env = helpers.loggedIn()
        local game = env.C_Map.GetPlayerMapPosition(1436, "player")
        local x, y = ns.Geometry.ToMap(ns.Geometry.MapRect(1436), -10603.8, 1154.0)
        assertNear(game.x, x)
        assertNear(game.y, y)
    end)
end)

describe("the minimap", function()
    it("is as many yards across as the client draws, by zoom, in and out of doors", function()
        local ns = helpers.loggedIn()
        assertNear(466.667, ns.Geometry.MinimapDiameter(0, false))
        assertNear(133.333, ns.Geometry.MinimapDiameter(5, false))
        assertNear(300, ns.Geometry.MinimapDiameter(0, true))
        assertNear(50, ns.Geometry.MinimapDiameter(5, true))
        assertNear(466.667, ns.Geometry.MinimapDiameter(nil, nil), 0.001, "no zoom reads as zoom 0")
    end)

    it("puts north up and west to the left", function()
        local ns = helpers.loggedIn()
        local right, up = ns.Geometry.MinimapOffset(0, 0, 10, 0)
        assertNear(0, right)
        assertNear(10, up)
        right, up = ns.Geometry.MinimapOffset(0, 0, 0, 10)
        assertNear(-10, right)
        assertNear(0, up)
    end)

    it("turns with the player when the minimap turns", function()
        local ns = helpers.loggedIn()
        local right, up = ns.Geometry.MinimapOffset(0, 0, 0, 10, math.pi / 2, true)
        assertNear(0, right, 0.001, "facing west, west is up")
        assertNear(10, up)
        right, up = ns.Geometry.MinimapOffset(0, 0, 10, 0, math.pi * 1.5, true)
        assertNear(-10, right, 0.001, "facing east, north is to the left")
        assertNear(0, up)
        right, up = ns.Geometry.MinimapOffset(0, 0, 0, 10, math.pi / 2, false)
        assertNear(-10, right, 0.001, "a still minimap ignores the facing")
    end)
end)
