local helpers = require("helpers")

describe("the minimap button's geometry", function()
    local ns = helpers.loadAddon()

    it("puts angle 0 to the right and 90 at the top", function()
        local x, y = ns.MinimapButton.PositionFor(0, 80)
        assertNear(80, x)
        assertNear(0, y)
        x, y = ns.MinimapButton.PositionFor(90, 80)
        assertNear(0, x)
        assertNear(80, y)
    end)

    it("turns a cursor offset back into an angle between 0 and 360", function()
        assertNear(0, ns.MinimapButton.AngleFor(10, 0))
        assertNear(90, ns.MinimapButton.AngleFor(0, 10))
        assertNear(225, ns.MinimapButton.AngleFor(-10, -10))
    end)
end)

describe("the minimap button", function()
    it("sits on the minimap with RareMob's skull", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual(env.Minimap, button:GetParent())
        assertEqual("Interface\\AddOns\\RareMob\\minimap", button.icon:GetTexture())
        assertEqual("table", type(ns.settings.button))
    end)

    it("opens and closes the list on a left-click", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnClick(button, "LeftButton")
        assertTrue(ns.List.Frame():IsShown())
        button.scripts.OnClick(button, "LeftButton")
        assertFalse(ns.List.Frame():IsShown())
    end)

    it("opens the settings on a right-click", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnClick(button, "RightButton")
        assertEqual("category-id", env.__openedCategory)
    end)

    it("says what its clicks do", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnEnter(button)
        assertEqual("RareMob", env.GameTooltip.text)
        assertMatch("[Rr]ight%-click", env.GameTooltip.lines[2].text)
    end)

    it("hides and comes back by command, remembered", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "minimap")
        assertTrue(ns.settings.button.hide)
        assertFalse(ns.MinimapButton.Button():IsShown())
        helpers.command(env, "minimap")
        assertFalse(ns.settings.button.hide)
        assertTrue(ns.MinimapButton.Button():IsShown())
    end)

    it("stays hidden at login when hidden before", function()
        local ns = helpers.loggedIn(function(env)
            env.RareMobDB = { settings = { button = { hide = true } } }
        end)
        assertFalse(ns.MinimapButton.Button():IsShown())
    end)
end)
