local helpers = require("helpers")

describe("the minimap button's geometry", function()
    local ns = helpers.loadAddon()

    it("puts angle 0 to the right and 90 at the top", function()
        local x, y = ns.MinimapButton.PositionFor(0, 80)
        assertNear(80, x)
        assertNear(0, y)
        x, y = ns.MinimapButton.PositionFor(90, 80)
        assertNear(0, x)
        assertNear(80, y)
    end)

    it("turns a cursor offset back into an angle between 0 and 360", function()
        assertNear(0, ns.MinimapButton.AngleFor(10, 0))
        assertNear(90, ns.MinimapButton.AngleFor(0, 10))
        assertNear(225, ns.MinimapButton.AngleFor(-10, -10))
    end)
end)

describe("the minimap button", function()
    it("sits on the minimap at the saved angle", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        assertEqual(env.Minimap, button:GetParent())
        local _, relativeTo, _, x, y = button:GetPoint(1)
        assertEqual(env.Minimap, relativeTo)
        assertTrue(x < 0 and y < 0, "the default angle is bottom-left")
    end)

    it("opens and closes the window on a click", function()
        local ns = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnClick(button, "LeftButton")
        assertTrue(ns.Window.Frame():IsShown())
        button.scripts.OnClick(button, "LeftButton")
        assertFalse(ns.Window.Frame():IsShown())
    end)

    it("follows the cursor around the rim while dragged, and saves the angle", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        env.Minimap.centerX, env.Minimap.centerY = 500, 500
        env.__cursorX, env.__cursorY = 500, 600
        button.scripts.OnDragStart(button)
        button.scripts.OnUpdate(button)
        button.scripts.OnDragStop(button)
        assertNear(90, ns.db.minimap.angle)
        assertNil(button.scripts.OnUpdate, "stops following once dropped")
    end)

    it("explains itself in a tooltip", function()
        local ns, env = helpers.loggedIn()
        local button = ns.MinimapButton.Button()
        button.scripts.OnEnter(button)
        assertEqual("BossLoot", env.GameTooltip.text)
    end)

    it("hides and shows with /bl minimap, remembering the choice", function()
        local ns, env = helpers.loggedIn()
        helpers.command(env, "minimap")
        assertFalse(ns.MinimapButton.Button():IsShown())
        assertTrue(ns.db.minimap.hide)
        helpers.command(env, "minimap")
        assertTrue(ns.MinimapButton.Button():IsShown())
    end)

    it("stays hidden at login when it was hidden before", function()
        local ns, env = helpers.loadAddon(nil, function(env)
            env.BossLootDB = { minimap = { hide = true, angle = 10 } }
        end)
        helpers.sampleInstances(ns)
        helpers.login(ns, env)
        assertFalse(ns.MinimapButton.Button():IsShown())
    end)
end)
